Repository redhat-developer/service-binding-operator, pull requests merged in 2019-07, with the labels that each got.

#35 Add Makefile target for CI
  Makefile
  hack/check-crds.sh
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.1.clusterserviceversion.yaml
  manifests/service-binding-operator/0.0.1/service-binding-operator.v0.0.1.clusterserviceversion.yaml
  manifests/service-binding-operator/service-binding-operator.package.yaml
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
  test/e2e/catalog_source.yaml
  test/e2e/subscription.yaml
Labels: approved, size/L

#44 Add objectName selector
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/S

#46 Adds changes from PR #39 - Flat structure in manifest
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.4.clusterserviceversion.yaml
Labels: size/M

#47 Release 0.0.6
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.v0.0.6.clusterserviceversion.yaml
Labels: size/S

#48 0.0.10 changes with fixed rolebindings
  Makefile
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.v0.0.10.clusterserviceversion.yaml
Labels: size/S

#49 Rename crd fields
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/controller_test.go
  pkg/controller/servicebindingrequest/planner.go
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/L

#51 Create a more readable help target
  Makefile
Labels: lgtm, size/L

#52 Add operator-courier lint, run operator locally and cleaning targets
  Makefile
Labels: lgtm, size/M

#53 Adding Unit-Testing on Retriever (Controller)
  Makefile
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
  test/operator-hub/catalog_source.yaml
  test/operator-hub/subscription.yaml
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/go.uber.org/atomic/.travis.yml
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/error.go
  vendor/modules.txt
Labels: size/XXL

#57 Change logic to replace image
  openshift-ci/Dockerfile.registry.build
Labels: size/XS

#56 Create virtual env for yamllint
  Makefile
  openshift-ci/Dockerfile.tools
Labels: lgtm, size/S

#54 First draft at expanded README file - to describe goals and usage of operator
  README.md
Labels: size/L

#50 Change channel from stable to alpha
  manifests/service-binding-operator.package.yaml
Labels: size/XS

#61 Remove a extra space
  manifests/service-binding-operator.package.yaml
Labels: size/XS

#55 [ODC-1240] More Unit and E2E Testing
  Makefile
  cmd/manager/main.go
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  hack/check-crds.sh
  manifests/service-binding-operator.v0.0.10.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/controller_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/mocks.go
  test/operator-hub/subscription.yaml
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: approved, lgtm, size/XXL

#60 The display name was "Operator Service Binding Operator"
  manifests/service-binding-operator.v0.0.10.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#62 Refactor test to use sub tests
  pkg/controller/servicebindingrequest/retriever_test.go
Labels: approved, lgtm, size/M

#64 Support dotted notation in attribute path
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#67 Use ResourceKind instead of ResourceName
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/planner.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/M

#72 Fix up the YAMLs in the readme
  README.md
Labels: approved, lgtm, size/L

#76 Readme Formatting and EditorConfig Settings
  .editorconfig
  README.md
Labels: approved, lgtm, size/L

#58 Replace docker by podman.
  Makefile
Labels: approved, lgtm, size/S

#79 Move planner into a separate package
  pkg/controller/servicebindingrequest/planner/planner.go
  pkg/controller/servicebindingrequest/planner/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
Labels: approved, lgtm, size/S

#80 Adding ConfigMap support for the controller
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#84 Install jq to root container for OpenShift CI.
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#85 Add prefixes for mount path and environment vars
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#87 Update example scenario in README.md
  README.md
  assets/operator-hub-pgo-screenshot.png
  assets/operator-hub-sbo-screenshot.png
Labels: approved, lgtm, size/L

#82 Add test coverage via Codecov
  .codecov.yaml
  Makefile
  README.md
Labels: approved, lgtm, size/M

#83 Bind secret values as files into the container
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/retriever.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#93 correct README typo
  README.md
Labels: approved, lgtm, size/XS

#95 Update CR
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
Labels: approved, lgtm, size/XS

#97 Make envVarPrefix optional
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS
