Repository redhat-developer/service-binding-operator, pull requests merged in 2019-06, with the labels that each got.

#14 Create Dockerfile for root image in OpenShift CI
  openshift-ci/Dockerfile.tools
Labels: size/M

#22 Use Go 1.12 binary from upstream
  openshift-ci/Dockerfile.tools
Labels: size/XS

#23 Create directory for Go installation
  openshift-ci/Dockerfile.tools
Labels: size/XS

#6 Create environment variables from OLM descriptors
  .travis.yml
  Makefile
  go.mod
  go.sum
  pkg/apis/addtoscheme_apps_v1alpha1.go
  pkg/controller/add_servicebindingrequest.go
  pkg/controller/servicebindingrequest/servicebindingrequest_controller.go
  pkg/controller/servicebindingrequest/servicebindingrequest_controller_test.go
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/apps/v1/doc.go
  vendor/github.com/openshift/api/apps/v1/generated.pb.go
  vendor/github.com/openshift/api/apps/v1/generated.proto
  vendor/github.com/openshift/api/apps/v1/register.go
  vendor/github.com/openshift/api/apps/v1/types.go
  vendor/github.com/openshift/api/apps/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/apps/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/LICENSE
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: size/XXL

#27 Create Makefile target to run unit tests
  Makefile
Labels: size/XS

#28 Set GOCACHE & GO111MODULE environment variables
  Makefile
Labels: size/XS

#29 Set GOCACHE for `go list` command
  Makefile
Labels: size/XS

#30 Add OWNERS list
  OWNERS
  test/OWNERS
Labels: size/M

#31 Convert namespace to lowercase
  Makefile
Labels: approved, lgtm, size/XS

#33 Package operator as a marketplace operator
  deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.package.yaml
  deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.servicebindingrequests.crd.yaml
  deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.v0.0.1.clusterserviceversion.yaml
Labels: size/L

#34 Allow GET on all namespace-scoped CRs
  deploy/role.yaml
Labels: size/XS

#36 Small makefile fixes
  Makefile
Labels: size/XS

#32 Add Dockerfile
  Dockerfile
  Makefile
Labels: size/M

#39 upgrade operator to 0.0.4
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.1.clusterserviceversion.yaml
  manifests/service-binding-operator.v0.0.4.clusterserviceversion.yaml
Labels: size/L
