Repository redhat-developer/service-binding-operator, pull requests merged in 2019-10, with the labels that each got.

#184 Add knative to role, bump to 0.0.20
  Makefile
  deploy/role.yaml
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.v0.0.20.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
Labels: size/L

#189 Update README to add test target
  README.md
Labels: approved, lgtm, size/XS

#181 Add knative example.
  README.md
  examples/knative_postgresql_customvar/Makefile
  examples/knative_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/service-binding-request.yaml
  hack/examples-commons.sh
  hack/yamls/knative-serving.yaml
  hack/yamls/operator-source.template.yaml
  hack/yamls/postgresql-database.yaml
  hack/yamls/service-mesh-control-plane.yaml
  hack/yamls/service-mesh-member-roll.yaml
  hack/yamls/subscription.template.yaml
Labels: approved, lgtm, size/XL

#190 Adding file to explain contribution process to community members.
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#192 Reduce and unify examples' Makefiles by using the Commons.
  examples/commons.mk
  examples/java_postgresql_customvar/Makefile
  examples/java_postgresql_customvar/backing-db-operator-source.yaml
  examples/java_postgresql_customvar/create-db-instance.yaml
  examples/java_postgresql_customvar/namespace.yaml
  examples/java_postgresql_customvar/service-binding-operator-source.yaml
  examples/knative_postgresql_customvar/Makefile
  examples/nodejs_awsrds_varprefix/Makefile
  examples/nodejs_awsrds_varprefix/operator-source.service-binding-operator.yaml
  examples/nodejs_postgresql/Makefile
Labels: approved, lgtm, size/XL

#185 Build using RHEL-based image
  Dockerfile.rhel
Labels: approved, lgtm, size/M

#197 Fix copy-paste typos in example commons.
  examples/commons.mk
Labels: approved, lgtm, size/M

#199 Minor changes to improve feedback to users when running examples
  hack/examples-commons.sh
Labels: approved, lgtm, size/XS

#194 Update golang, kubectl, and operator-sdk version to latest in CI
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#200 update GolangCI Lint version
  Makefile
Labels: approved, lgtm, size/XS

#201 Add go version in go.mod
  go.mod
Labels: approved, lgtm, needs-ok-to-test, size/XS

#202 Fix operator uninstallers in example commons.
  examples/commons.mk
Labels: approved, lgtm, size/XS

#195 Unify and split logging into levels to reduce log flooding in production
  Makefile
  cmd/manager/main.go
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/mapper.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/watch.go
  pkg/log/log.go
Labels: approved, lgtm, size/XL

#204 fixes golangci
  pkg/controller/servicebindingrequest/olm.go
Labels: approved, lgtm, size/XS

#207 fixes yaml lint
  .codecov.yaml
Labels: approved, lgtm, size/XS

#206 tiny typo
  examples/nodejs_postgresql/README.md
Labels: approved, lgtm, size/XS

#186 Bind configmap, secret, service, route when binding annotations are not provided
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  go.mod
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/bind_custom_resources.go
  pkg/controller/servicebindingrequest/bind_custom_resources_test.go
  pkg/controller/servicebindingrequest/custom_env_parser.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#209 Add test-e2e-image target to run test on operator image
  Makefile
Labels: approved, lgtm, size/S

#212 Removes matchLabels and resourceRef from required
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  pkg/controller/servicebindingrequest/binder.go
Labels: approved, lgtm, size/XS

#205 Add etcd operator binding example
  examples/nodejs_etcd_operator/README.md
Labels: approved, lgtm, size/M

#215 Make attributes not required
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
Labels: approved, lgtm, size/XS

#158 Extend automated E2E tests to permute order of Backing service, Application and Service Binding Request
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/L

#77 Prepare repo for the OpenShift Automated Release
  Dockerfile.ocp
Labels: approved, lgtm, size/M

#216 Enable the 'update' privilege for the service account so that CRs can be updated.
  deploy/role.yaml
  manifests/service-binding-operator.v0.0.20.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#218 Update golang version to 1.13 and optimize/speed-up build
  Dockerfile.rhel
Labels: approved, lgtm, size/S

#217 Add label for appregistry=true
  Dockerfile.ocp
  Dockerfile.rhel
Labels: approved, lgtm, size/M

#219 Nested manifest structure
  manifests/0.0.20/service-binding-operator.v0.0.20.clusterserviceversion.yaml
  manifests/0.0.20/servicebindingrequests.apps.openshift.io.crd.yaml
  manifests/service-binding-operator.package.yaml
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/S

#221 Use @otaviof's hack script to get operator log from e2e tests.
  Makefile
  hack/e2e-log-parser.sh
Labels: approved, lgtm, size/S

#220 Layout manifests for ART/downstream & upstream
  manifests-upstream/0.0.20/service-binding-operator.v0.0.20.clusterserviceversion.yaml
  manifests-upstream/0.0.20/servicebindingrequests.apps.openshift.io.crd.yaml
  manifests-upstream/service-binding-operator.package.yaml
  manifests/4.3.0/service-binding-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3.0/servicebindingrequests.apps.openshift.io.crd.yaml
  manifests/service-binding-operator.package.yaml
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/L

#224 Select target object field by metadata.name
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
Labels: lgtm, size/S

#179 Skip adding annotations to the Deployment
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm, size/XS

#180 Initial draft of operators' best practices guide
  README.md
  docs/OperatorBestPractices.md
  examples/java_postgresql_customvar/README.md
  examples/nodejs_postgresql/README.md
Labels: approved, lgtm, size/L

#226 Fix the e2e test failure masking.
  Makefile
  hack/e2e-log-parser.sh
Labels: lgtm, size/S

#229 Update README.md with etcd example link
  README.md
Labels: approved, lgtm, size/XS
