Repository redhat-developer/service-binding-operator, pull requests merged in 2019-11, with the labels that each got.

#231 docs: Update to include standard podSpec
  README.md
Labels: size/XS

#230 Intermediate secret && configMap update
  pkg/controller/servicebindingrequest/sbrcontroller.go
Labels: approved, lgtm, size/XS

#208 Add a consistent-crds target
  Makefile
  pkg/controller/servicebindingrequest/binder.go
Labels: approved, lgtm, size/S

#232 Update 4.3 CRD
  manifests/4.3.0/service-binding-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3.0/servicebindingrequests.apps.openshift.io.crd.yaml
Labels: size/M

#193 Adds a version-update target for bumping up a version
  Makefile
  hack/update-version.sh
Labels: size/M

#183 Read metadata from CRD annotations
  Makefile
  go.mod
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/e2e/annotation_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: size/XL

#235 fix a typo
  README.md
Labels: ok-to-test, size/XS

#241 changes assert to require
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/XS

#242 Add remaining permutations to the SBR e2e test.
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/S

#245 Configure release
  .github/workflows/nightly-release.yml
Labels: size/S

#250 Update description field in CSV
  manifests-upstream/0.0.20/service-binding-operator.v0.0.20.clusterserviceversion.yaml
  manifests/4.3/service-binding-operator.v4.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#253 tiny typo
  README.md
Labels: size/XS

#239 Removed Old Dockerfile
  Dockerfile
Labels: approved, lgtm, size/M

#254 Adds a target for merge to master dev release
  .travis.yml
  Makefile
Labels: size/S

#258 add PR template
  docs/pull_request_template.md
Labels: lgtm, size/S

#259 Update to match OpenShift 4.3 change for sample app - nodejs_postgresql
  examples/nodejs_postgresql/Makefile
  examples/nodejs_postgresql/README.md
  examples/nodejs_postgresql/service-binding-operator-source.yaml
  examples/nodejs_postgresql/service-binding-request.yaml
Labels: approved, lgtm, size/L

#262 Update the Knative example to be in synch with OpenShift 4.3
  examples/knative_postgresql_customvar/Makefile
  examples/knative_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/service-binding-request.yaml
  examples/knative_postgresql_customvar/serving.yaml
Labels: approved, lgtm, size/L

#260 Update example Java PostgreSQL example
  examples/java_postgresql_customvar/Makefile
  examples/java_postgresql_customvar/README.md
  examples/java_postgresql_customvar/service-binding-request.yaml
Labels: approved, lgtm, size/M
