Repository redhat-developer/service-binding-operator, pull requests merged in 2019-08, with the labels that each got.

#92 Add environment variable prefix
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/M

#100 Fix typo in README
  README.md
Labels: approved, lgtm, size/XS

#99 add UPDATE predicate to avoid reconcile events when status is updated
  pkg/controller/servicebindingrequest/controller.go
Labels: approved, lgtm, size/S

#98 Exposes service binding request status
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/status.go
Labels: approved, lgtm, size/M

#104 Adds status information in README
  README.md
Labels: approved, lgtm, size/XS

#103 Adds secret name in service binding status
  README.md
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/status.go
Labels: approved, lgtm, size/S

#105 Adds ApplicationObjects in status
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/status.go
Labels: approved, lgtm, size/S

#107 Fix readme title
  README.md
Labels: size/XS

#109 Ignore broken packages for the time being
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: size/XS

#111 Disable lint temporarily
  Makefile
Labels: size/XS

#113 Add mountPathPrefix spec field in the example
  README.md
Labels: approved, lgtm, size/XS

#108 Remove sdk generated code for pod creation
  pkg/controller/servicebindingrequest/controller.go
Labels: approved, lgtm, size/S

#101 Add wait in reconcile loop.
  pkg/controller/servicebindingrequest/planner/planner.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/resourcepoll/wait.go
Labels: approved, lgtm, size/M

#118 Check if application object name is already present
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm, size/M

#115 Release 0.0.16
  Makefile
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.16.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/M

#120 Add lint back
  Dockerfile
  Makefile
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#125 Fixed typo in the README
  README.md
Labels: approved, lgtm, size/XS

#123 Use Group/Version/Kind for both ApplicationSelector & BackingServiceSelector
  Makefile
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/planner/planner.go
  pkg/controller/servicebindingrequest/reconciler.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#124 Add a Binder which uses a dynamic client to CRUD deployment objects
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  go.sum
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner/planner.go
  pkg/controller/servicebindingrequest/planner/planner_test.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/status.go
  pkg/resourcepoll/wait.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/README.md
  test/mocks/fake.go
  test/mocks/mocks.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#130 Update CRD manifest for release v0.0.17
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#129 Release v0.0.17
  Makefile
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.17.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#128 Add 'Binding AWS RDS+envVarPrefix' example scenario.
  assets/operator-hub-awsrdso-screenshot.png
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/Makefile
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/README.md
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/build-config.shell-app.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/deployment-config.shell-app.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/image-stream.shell-app.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/operator-source.aws-rds-operator.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/operator-source.service-binding-operator.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/rds.mydb.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/secret.aws-rds-operator.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/secret.mydb.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/service-binding-request.nodejs-app.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/service-binding-request.shell-app.yaml
Labels: approved, lgtm, size/XL

#121 Add examples dir, move initial scenario into examples dir
  README.md
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/backing-db-operator-source.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/create-db-instance.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/namespace.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-operator-source.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-request.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/deployment-config.shell-app.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/secret.aws-rds-operator.yaml
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/secret.mydb.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.17.clusterserviceversion.yaml
Labels: approved, lgtm, size/XL

#133 Fix PascalCase in constant values stored in ServiceBindRequest's Status field
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#137 Move PostgreSQL Operator to samples repo
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
  go.mod
  go.sum
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/LICENSE
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/addtoscheme_postgresql_v1alpha1.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/apis.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/postgresql/v1alpha1/database_types.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/postgresql/v1alpha1/doc.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/postgresql/v1alpha1/register.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/postgresql/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-backing-service-samples/postgresql-operator/pkg/apis/postgresql/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#132 Make the annotations shorter
  README.md
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
Labels: lgtm, size/M

#141 release 0.0.18
  Makefile
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.v0.0.18.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/S

#146 Update example's makefile to show build targets
  examples/bind_imported_app_to_offcluster_operator_managed_AWS_RDS_db/Makefile
Labels: approved, lgtm, size/M

#127 Force triggering of a deployment whenever reconcile causes change in bound data
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
Labels: approved, lgtm, size/M

#134 Add OPTIONAL triggerRebinding field in the Spec
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/reconciler_whitebox_test.go
Labels: approved, lgtm, size/L

#136 Add shortNames to Servicebindingrequest in CRD
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#157 Upgrade controller runtime version
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/M

#156 Fix a broken link to an image file
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
Labels: approved, lgtm, size/XS
