Repository redhat-developer/service-binding-operator, pull requests merged in 2019-09, with the labels that each got.

#161 Added in sleep statement that is referenced, but is missing
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/XS

#139 Fix: Requeue if deployment/deploymentconfig not found
  pkg/controller/servicebindingrequest/binder.go
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/L

#163 Correct small errors and a link in readme of an example.
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
Labels: approved, lgtm, size/XS

#170 Update the original (in-cluster) example to include a Makefile
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/Makefile
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/backing-db-operator-source.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/create-db-instance.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/namespace.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-operator-source.yaml
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-request.yaml
Labels: approved, lgtm, size/L

#169 Added file to list names of project contributors
  contributors.txt
Labels: approved, lgtm, size/S

#168 Updated reference to deployed app in example README
  examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
Labels: approved, lgtm, size/XS

#171 Reverting Trigger Rebinding
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/reconciler_whitebox_test.go
Labels: approved, lgtm, size/L

#162 Adding Watches when a CSV is Created/Updated
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/annotations_test.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/mapper.go
  pkg/controller/servicebindingrequest/namespacedname.go
  pkg/controller/servicebindingrequest/namespacedname_test.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/watch.go
Labels: approved, lgtm, size/XL

#166 Object Updates as Last Reconciliation Step
  Makefile
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#159 Feat: Add custom env support
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/custom_env_parser.go
  pkg/controller/servicebindingrequest/custom_env_parser_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#176 Release 0.0.19
  Makefile
  manifests/service-binding-operator.package.yaml
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  manifests/service-binding-operator.v0.0.18.clusterserviceversion.yaml
  manifests/service-binding-operator.v0.0.19.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
Labels: lgtm, size/L

#174 Add java app sample
  README.md
  examples/app_to_incluster_operator_managed_PostgreSQL_db/Makefile
  examples/app_to_incluster_operator_managed_PostgreSQL_db/README.md
  examples/app_to_incluster_operator_managed_PostgreSQL_db/backing-db-operator-source.yaml
  examples/app_to_incluster_operator_managed_PostgreSQL_db/create-db-instance.yaml
  examples/app_to_incluster_operator_managed_PostgreSQL_db/namespace.yaml
  examples/app_to_incluster_operator_managed_PostgreSQL_db/service-binding-operator-source.yaml
  examples/app_to_incluster_operator_managed_PostgreSQL_db/service-binding-request.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/Makefile
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/README.md
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/build-config.shell-app.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/deployment-config.shell-app.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/image-stream.shell-app.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/operator-source.aws-rds-operator.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/operator-source.service-binding-operator.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/rds.mydb.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/secret.aws-rds-operator.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/secret.mydb.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/service-binding-request.nodejs-app.yaml
  examples/app_to_offcluster_operator_managed_AWS_RDS_db/service-binding-request.shell-app.yaml
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/Makefile
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/README.md
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/backing-db-operator-source.yaml
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/create-db-instance.yaml
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/namespace.yaml
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-operator-source.yaml
  examples/java_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-request.yaml
Labels: approved, lgtm, size/L

#173 Support specification of the 'application' object name.
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
  go.sum
  manifests/service-binding-operator.servicebindingrequests.crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#178 Ensure lastbound env key is not added multiple times
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
Labels: lgtm, size/M
