Repository redhat-developer/service-binding-operator, pull requests merged in 2019-12, with the labels that each got.

#256 Unbinding: Handling Resource Deletion
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/annotations_test.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/sbrcontroller_test.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/XXL

#267 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#265 Fix double base64 encoding for customEnvVar (#264)
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#247 Test to validate binding a backing service with a DeploymentConfig
  pkg/controller/servicebindingrequest/bind_custom_resources.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, e2e, lgtm, size/L

#274 Test to verify binding a single backing service with two individual applications
  pkg/controller/servicebindingrequest/binder_test.go
Labels: approved, lgtm, size/M

#268 Update RDS example to match 4.3 Deployments and SBO use of resourceRefs
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_awsrds_varprefix/namespace.yaml
  examples/nodejs_awsrds_varprefix/service-binding-request.nodejs-app.yaml
  examples/nodejs_awsrds_varprefix/service-binding-request.shell-app.yaml
Labels: approved, lgtm, size/M

#277 Add a readme to the dir build/
  build/README.md
Labels: approved, lgtm, size/XS

#273 Use corev1.EnvVar instead of CustomEnvMap
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/custom_env_parser.go
  pkg/controller/servicebindingrequest/custom_env_parser_test.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#280 Cleaning up openshift-ci for unwanted steps
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
Labels: approved, lgtm, size/S

#278 Make serialization options consistent with the published CRD
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Labels: approved, lgtm, size/XS

#279 Fix backing service CRD annotations' parsing
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/annotations_test.go
  pkg/controller/servicebindingrequest/bindinginfo.go
  pkg/controller/servicebindingrequest/bindinginfo_test.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
  pkg/controller/servicebindingrequest/planner.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/mocks.go
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: approved, lgtm, size/XL

#257 Remove upstream manifests
  manifests-upstream/0.0.20/service-binding-operator.v0.0.20.clusterserviceversion.yaml
  manifests-upstream/0.0.20/servicebindingrequests.apps.openshift.io.crd.yaml
  manifests-upstream/service-binding-operator.package.yaml
Labels: approved, lgtm, size/L

#263 e2e etcd operator test
  Makefile
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/servicebindingrequest/secret_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/etcd_operator_mocks.go
  test/mocks/fake.go
  test/mocks/mocks.go
  test/third-party-crds/etcd_v1beta2_etcdcluster_crd.yaml
  vendor/github.com/coreos/etcd-operator/LICENSE
  vendor/github.com/coreos/etcd-operator/NOTICE
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/backup_types.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/cluster.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/cluster_tls.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/doc.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/register.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/restore_types.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/status.go
  vendor/github.com/coreos/etcd-operator/pkg/apis/etcd/v1beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, automation tests, e2e, lgtm, size/XXL

#281 Reuse retrieve.Cache for customEnvParser in secret.go
  pkg/controller/servicebindingrequest/custom_env_parser_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
Labels: approved, lgtm, size/M
