Repository redhat-developer/service-binding-operator, pull requests merged in 2020-04, with the labels that each got.

#367 Use any resource as a backing service
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
Labels: approved, lgtm, size/L

#412 Introduce "json" function in templating to generate inline "json" as custom env var
  pkg/controller/servicebindingrequest/custom_env_parser.go
  pkg/controller/servicebindingrequest/custom_env_parser_test.go
Labels: approved, lgtm, ok-to-test

#414 Status should be updated when application selector is missing
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  test/mocks/fake.go
Labels: approved, lgtm

#416 remove duplicated env when read secret
  pkg/controller/servicebindingrequest/retriever.go
Labels: approved, lgtm, ok-to-test

#424 Remove binding status
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/nodejs_postgresql/README.md
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm

#430 check SBR deletion before calling retriever.Get()
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/binding_test.go
Labels: approved, lgtm, ok-to-test

#426 add extraFieldsModifier to binder
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
Labels: approved, lgtm, ok-to-test

#427 Delete the sbr even when application has been previously deleted
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm

#433 fix csv resource checking
  pkg/controller/servicebindingrequest/sbrcontroller.go
Labels: approved, lgtm, ok-to-test

#432 fixes generic binding
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/planner.go
Labels: approved, lgtm

#428 Add an envVarPrefix field to backingServiceSelector
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/related_resources.go
  pkg/controller/servicebindingrequest/retrieve_decoupled.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
Labels: approved, lgtm, ok-to-test

#437 Remove redundant checking
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm

#438 use 0.0.23 CSV version as template when generating a new one
  Makefile
Labels: approved, lgtm
