Repository redhat-developer/service-binding-operator, pull requests merged in 2020-01, with the labels that each got.

#283 Implement workaround for GOFLAGS
  .travis.yml
Labels: approved, lgtm, size/XS

#288 Mark matchLabels as optional
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#289 Avoiding Repeated Finalizers
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm, size/XS

#275 separate Secret and configmap switch case
  pkg/controller/servicebindingrequest/bind_custom_resources.go
  pkg/controller/servicebindingrequest/bind_custom_resources_test.go
Labels: approved, lgtm, size/M

#282 Ensure MountPathPrefix is optional
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Labels: approved, lgtm, size/XS

#292 Fixes go mod invalid pseudo-version error
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#269 Add targets and travis CI setup for merge to master dev releases
  .travis.yml
  Makefile
  deploy/olm-catalog/README.md
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
  deploy/olm-catalog/service-binding-operator/service-binding-operator.package.yaml
  go.mod
  go.sum
  hack/add-info-to-csv.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#294 fixes automated travis releases
  .travis.yml
  Makefile
Labels: approved, lgtm, size/XS

#291 Use Kubernetes label selector
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/reconciler.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/M

#295 Update examples with label selectors
  Makefile
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
  deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
Labels: approved, lgtm, size/L

#299 Increment operator version to 0.0.24
  Makefile
Labels: approved, lgtm, size/XS

#301 Do proper tagging for operator images
  Makefile
Labels: approved, lgtm, size/XS

#298 Use GroupVersionResource in ApplicationSelector
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binder.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/S

#302 Use GroupVersionKind in BackingServiceSelector
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/servicebindingrequest/sbrcontroller_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/M

#303 Remove unwanted YAML struct tag
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Labels: approved, lgtm, size/XS

#304 Have a consistent SBR mock
  test/mocks/mocks.go
Labels: approved, lgtm, size/XS

#305 Rename gr to gvr
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm, size/S

#307 Updates deploy cr
  deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
Labels: approved, lgtm, size/XS

#308 make resourceref of applicationSelector as optional
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/XS

#309 Add CSVstep in e2e scenario-csv-db-app-sbr
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm, size/XS

#310 Update csv mock, add selector and containers.
  test/mocks/mocks.go
Labels: approved, lgtm, size/S
