Repository redhat-developer/service-binding-operator, pull requests merged in 2020-08, with the labels that each got.

#593 Add acceptance test scenario: Bind 2 backing services to a single application.
  test/acceptance/features/bindToService.feature
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#599 Fix etcd-nodejs example readme
  examples/nodejs_etcd_operator/README.md
Labels: approved, lgtm

#598 Sunder the present feature file
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
Labels: approved, lgtm

#596 Deprecate relationship annotations
  pkg/controller/servicebindingrequest/mapper.go
  pkg/controller/servicebindingrequest/mapper_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/servicebinder.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/etcd_operator_mocks.go
  test/mocks/mocks.go
Labels: approved, lgtm

#607 Update README.md to reflect our goal
  README.md
Labels: approved, lgtm

#616 docs: Backing service needn't be provided by operators only
  README.md
Labels: approved, lgtm

#634 [acceptance-tests] Increase various timeouts to make acceptance tests less flaky
  hack/deploy-sbo-local.sh
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#619 Remove flaky test `TestAddSchemesToFramework/end-to-end/scenario-sbr-app-db`
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm

#602 Updates java-postgresql example to demonstrate use of annotations to fetch data from scalar, sequence, map data structures
  examples/java_postgresql_customvar/README.md
  examples/java_postgresql_customvar/service-binding-request.yaml
Labels: approved, lgtm

#567 Acceptance tests-quarkus_posgresql_as_knative_service
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/steps/command.py
  test/acceptance/features/steps/knative_serving.py
  test/acceptance/features/steps/namespace.py
  test/acceptance/features/steps/nodejs_application.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/postgres_db.py
  test/acceptance/features/steps/quarkus_application.py
  test/acceptance/features/steps/quarkus_s2i_builder_image.py
  test/acceptance/features/steps/serverless_operator.py
  test/acceptance/features/steps/service_binding_request.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm, ok-to-test

#638 [acceptance-tests] Fix negative corner cases handling env variables
  test/acceptance/features/steps/command.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#513 Support custom containers path and secret path
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  examples/pod_spec_path/README.md
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/servicebinder.go
  pkg/controller/servicebindingrequest/servicebinder_test.go
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
  test/mocks/mocks.go
Labels: approved, lgtm

#643 Add link to mailing list info page
  README.md
Labels: approved, documentation, lgtm

#618 docs: Update best practices
  README.md
  docs/BackingServiceBestPractices.md
Labels: approved, lgtm

#649 fix issue #648 , service-binding-operator panics if there is a configMapRef in envFrom
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
Labels: approved, lgtm, ok-to-test

#645 [acceptance-tests] Fix multiservice step to work with both oc v4.5 and v4.6
  test/acceptance/features/steps/quarkus_application.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#651 Remove non-active committer
  OWNERS
Labels: approved, lgtm

#647 Document containersPath and secretPath behavior
  docs/binding-path.md
Labels: approved, documentation, lgtm
