Repository redhat-developer/service-binding-operator, pull requests merged in 2020-05, with the labels that each got.

#447 Add example for any resource as a backing service
  examples/route_k8s_resource/README.md
Labels: approved, lgtm

#434 Add a choice of installing SBO either from community or master in examples
  examples/commons.mk
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_ibmcloud_operator/README.md
  examples/nodejs_postgresql/README.md
  hack/examples-commons.sh
Labels: approved, lgtm

#444 Separate SetSBRAnnotations/RemoveSBRAnnotations functions
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/annotations_test.go
  pkg/controller/servicebindingrequest/binding.go
Labels: approved, lgtm, ok-to-test

#436 Validate version number against version in the community operator repo
  Makefile
  hack/validate-release.sh
Labels: approved, lgtm

#452 Update OWNERS
  OWNERS
Labels: approved, lgtm

#407 Streamline data retrieval based on annotations
  Makefile
  go.mod
  pkg/conditions/conditions.go
  pkg/controller/servicebindingrequest/annotations/annotations.go
  pkg/controller/servicebindingrequest/annotations/attribute.go
  pkg/controller/servicebindingrequest/annotations/attribute_test.go
  pkg/controller/servicebindingrequest/annotations/bindinginfo.go
  pkg/controller/servicebindingrequest/annotations/bindinginfo_test.go
  pkg/controller/servicebindingrequest/annotations/configmap.go
  pkg/controller/servicebindingrequest/annotations/configmap_test.go
  pkg/controller/servicebindingrequest/annotations/errors.go
  pkg/controller/servicebindingrequest/annotations/resource.go
  pkg/controller/servicebindingrequest/annotations/resource_test.go
  pkg/controller/servicebindingrequest/annotations/secret.go
  pkg/controller/servicebindingrequest/annotations/secret_test.go
  pkg/controller/servicebindingrequest/bind_custom_resources.go
  pkg/controller/servicebindingrequest/bind_custom_resources_test.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/bindinginfo.go
  pkg/controller/servicebindingrequest/bindinginfo_test.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/custom_env_parser_test.go
  pkg/controller/servicebindingrequest/envvars/envvars.go
  pkg/controller/servicebindingrequest/envvars/envvars_test.go
  pkg/controller/servicebindingrequest/nested/accumulator/accumulator.go
  pkg/controller/servicebindingrequest/nested/nested.go
  pkg/controller/servicebindingrequest/nested/nested_test.go
  pkg/controller/servicebindingrequest/nested/path.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/plan_decoupled.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/related_resources.go
  pkg/controller/servicebindingrequest/retrieve_decoupled.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  pkg/controller/servicebindingrequest/service.go
  pkg/controller/servicebindingrequest/service_test.go
  pkg/controller/servicebindingrequest/servicebinder.go
  pkg/controller/servicebindingrequest/servicebinder_test.go
  pkg/controller/servicebindingrequest/servicecontext.go
  pkg/controller/servicebindingrequest/servicecontext_test.go
  pkg/testutils/testutils.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/README.md
  test/mocks/etcd_operator_mocks.go
  test/mocks/fake.go
  test/mocks/mocks.go
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: approved, lgtm

#473 Remove unnecessary comment
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Labels: approved, lgtm

#386 update go version
  .travis.yml
  Dockerfile.rhel
  go.mod
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#484 fixes `make local` CLI
  vendor/modules.txt
Labels: approved, lgtm

#494 remove empty yaml
  test/e2e/empty.yaml
Labels: approved, lgtm

#457 Use dynamic client to interact with the API server
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/controller.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/servicebinder.go
  pkg/controller/servicebindingrequest/servicebinder_test.go
  pkg/testutils/testutils.go
  test/mocks/fake.go
Labels: approved, lgtm, needs-ok-to-test

#496 Updates ServiceBindingRequestStatus.Applications documentation comment
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Labels: approved, lgtm
