Repository redhat-developer/service-binding-operator, pull requests merged in 2020-07, with the labels that each got.

#533 fixed CI unit jobs
  Makefile
Labels: lgtm

#524 Add owner reference to secret
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  pkg/controller/servicebindingrequest/servicebinder.go
Labels: approved, lgtm

#540 added link to Binding an Imported App to a Route/Ingress
  README.md
Labels: approved, lgtm

#519 Add notes to debug e2e tests
  docs/ci.md
Labels: lgtm

#534 Fix random e2e failure.
  Makefile
  go.mod
  go.sum
  test/e2e/servicebindingrequest_test.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, lgtm

#544 Make test namespace shorter to avoid having invalid - too long - URLs
  Makefile
Labels: approved, lgtm

#514 Add unit test to verify binding two ServiceBindingRequests with a single application
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm

#527 Fixed SBR request in route_k8s_resource example, by setting group of applicationSelector and fixing whitespaces for easier copy/pasting. #526
  examples/route_k8s_resource/README.md
Labels: approved, lgtm, needs-ok-to-test

#545 Proper render for the route_k8s_link in the readme.md
  README.md
Labels: approved, lgtm

#559 The framework's olm-catalog doc now resides at a new place
  deploy/olm-catalog/README.md
Labels: approved, lgtm

#556 Temporarily disable e2e scenarios not supported by SBO.
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm

#562 Use yamllint==1.23.0
  Makefile
Labels: approved, lgtm

#498 Split BindingReady into CollectionReady and InjectionReady
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/service.go
  pkg/controller/servicebindingrequest/servicebinder.go
  pkg/controller/servicebindingrequest/servicebinder_test.go
  test/e2e/servicebindingrequest_test.go
Labels: approved

#565 Split BindingReady into CollectionReady and InjectionReady
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/service.go
  pkg/controller/servicebindingrequest/servicebinder.go
  pkg/controller/servicebindingrequest/servicebinder_test.go
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm

#522 Revert annotation handling mechanism to not use the original config map or secret resource name location
  pkg/controller/servicebindingrequest/annotations/configmap_test.go
  pkg/controller/servicebindingrequest/annotations/errors.go
  pkg/controller/servicebindingrequest/annotations/resource.go
  pkg/controller/servicebindingrequest/annotations/secret_test.go
  pkg/controller/servicebindingrequest/envvars/envvars.go
  pkg/controller/servicebindingrequest/nested/accumulator/accumulator.go
  pkg/controller/servicebindingrequest/nested/path.go
Labels: approved, lgtm

#515 Fix bug where binding data is expected to overwrite the related resource name
  Makefile
  pkg/controller/servicebindingrequest/annotations/annotations.go
  pkg/controller/servicebindingrequest/annotations/resource.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/service.go
  pkg/controller/servicebindingrequest/service_test.go
  pkg/controller/servicebindingrequest/servicecontext.go
  pkg/controller/servicebindingrequest/servicecontext_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: approved, lgtm

#541 Add acceptance tests - nodejs_postgresql
  .gitignore
  Makefile
  hack/check-python/check-PEP8-style.sh
  hack/check-python/check-python-docstyle.sh
  hack/check-python/detect-common-errors.sh
  hack/check-python/detect-dead-code.sh
  hack/check-python/lint-python-code.sh
  hack/check-python/measure-cyclomatic-complexity.sh
  hack/check-python/measure-maintainability-index.sh
  hack/check-python/prepare-env.sh
  hack/deploy-sbo-local.sh
  hack/deploy-sbo-operator-hub.sh
  setup.cfg
  test/acceptance/README.md
  test/acceptance/features/bindToService.feature
  test/acceptance/features/environment.py
  test/acceptance/features/requirements.txt
  test/acceptance/features/steps/command.py
  test/acceptance/features/steps/dboperator.py
  test/acceptance/features/steps/namespace.py
  test/acceptance/features/steps/nodejs_application.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/postgres_db.py
  test/acceptance/features/steps/service_binding_request.py
  test/acceptance/features/steps/servicebindingoperator.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#558 Make logs more articulate.
  test/e2e/servicebindingrequest_test.go
Labels: approved, lgtm

#568 Add roles for crds and routes
  deploy/role.yaml
Labels: approved, lgtm

#523 Fix infinite reconcile loop
  pkg/controller/servicebindingrequest/annotations.go
  pkg/controller/servicebindingrequest/annotations_test.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm

#566 Ran operator-sdk generate crds on master
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
Labels: approved, lgtm

#551 Delete sbr if it's ownerRef resource is deleted
  pkg/controller/servicebindingrequest/reconciler.go
Labels: approved, lgtm

#572 [acceptance-tests] Unify python's venv.
  .gitignore
  Makefile
  hack/check-python/check-PEP8-style.sh
  hack/check-python/check-python-docstyle.sh
  hack/check-python/detect-common-errors.sh
  hack/check-python/detect-dead-code.sh
  hack/check-python/measure-cyclomatic-complexity.sh
  hack/check-python/measure-maintainability-index.sh
  hack/check-python/prepare-env.sh
Labels: approved, lgtm

#574 [acceptance-tests] Remove killall line before starting local SBO
  hack/deploy-sbo-local.sh
Labels: approved, lgtm

#576 [acceptance-tests] Generate test results in JUnit XML/xUnit format.
  Makefile
Labels: approved, lgtm

#580 Add .kube cache dir to .gitignore
  .gitignore
Labels: approved, lgtm

#577 Use file path as target
  Makefile
Labels: approved, lgtm

#578 [acceptance-tests] Kill local sbo process before running acceptance tests.
  hack/deploy-sbo-local.sh
Labels: approved, lgtm

#579 Update examples for customEnvVar
  examples/java_postgresql_customvar/README.md
  examples/java_postgresql_customvar/service-binding-request.yaml
  examples/knative_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/service-binding-request.yaml
Labels: approved, lgtm

#582 Remove an unused target and Makefile cleanup
  Makefile
Labels: approved, lgtm

#588 [acceptance-tests] Enable test artifacts gathering in CI
  Makefile
  hack/deploy-sbo-local.sh
Labels: approved, lgtm

#589 [acceptance-tests] Move setup-related dependencies to test-acceptance-setup
  Makefile
Labels: approved, lgtm

#573 [acceptance-tests] Replace deprecated OperatorSource by CatalogSource.
  test/acceptance/features/steps/dboperator.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#521 make custom_env_var can reference the whole secret/configmap without using a slash
  pkg/controller/servicebindingrequest/annotations/attribute.go
  pkg/controller/servicebindingrequest/annotations/bindinginfo.go
  pkg/controller/servicebindingrequest/annotations/bindinginfo_test.go
  pkg/controller/servicebindingrequest/annotations/configmap_test.go
  pkg/controller/servicebindingrequest/annotations/resource.go
  pkg/controller/servicebindingrequest/annotations/secret_test.go
  pkg/controller/servicebindingrequest/nested/path.go
Labels: approved, lgtm, ok-to-test

#592 Update docs for customEnvVar
  examples/java_postgresql_customvar/README.md
  examples/java_postgresql_customvar/service-binding-request.yaml
  examples/knative_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/service-binding-request.yaml
Labels: approved, lgtm

#591 [acceptance-tests] Fix python linting - dead code detection
  hack/check-python/detect-dead-code.sh
Labels: approved, lgtm

#583 Reconcile should log error if a resource is not found in detect Bindable resource
  pkg/controller/servicebindingrequest/service.go
  pkg/controller/servicebindingrequest/servicecontext.go
  pkg/controller/servicebindingrequest/servicecontext_test.go
Labels: approved, lgtm
