Repository redhat-developer/service-binding-operator, pull requests merged in 2020-09, with the labels that each got.

#662 Add link to SBO channel in Kubernetes slack workspace
  README.md
Labels: approved, lgtm

#659 Mark e2e testsuite obsolete and disable it before removal.
  Makefile
Labels: approved, lgtm

#610 docs: Enhancement proposal process
  CONTRIBUTING.md
  docs/proposals/README.md
  docs/proposals/guidelines/proposal-template.md
Labels: approved, lgtm

#666 [acceptance-tests] Check SBR status after the SBR step before checking the desired binding outcome
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
Labels: approved, lgtm

#639 Remove SBR finalizers in the test namespace before deleting the namespace
  Makefile
  hack/deploy-clean.sh
  hack/e2e-cleanup.sh
  hack/remove-sbr-finalizers.sh
Labels: approved, lgtm

#597 Trigger reconcile on updates to services' status
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/sbrcontroller_test.go
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
  test/acceptance/resources/backend.operator.manifest.yaml
Labels: approved, lgtm

#669 [acceptnace-tests] Enable running specific features or scenarios by tag expression
  Makefile
Labels: approved, lgtm

#670 update etcd example README
  examples/nodejs_etcd_operator/README.md
Labels: approved, lgtm, needs-ok-to-test

#640 Remove global & service prefixes from customEnvVar
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  test/acceptance/features/bindAppToService.feature
Labels: approved, lgtm

#676 [acceptance-tests] Fix python linting dependencies.
  hack/check-python/prepare-env.sh
  hack/check-python/requirements.txt
  test/acceptance/features/requirements.txt
Labels: approved, lgtm

#673 Test secret & configmap values
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#653 Prepare for 0.2.0 release
  Makefile
  deploy/olm-catalog/service-binding-operator/service-binding-operator.package.yaml
  docs/community-release.md
  test/operator-hub/subscription2.yaml
Labels: approved, lgtm

#620 Acceptance test for validating binding using OLM descriptors
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#613 [acceptance-tests] Add scenario to validate etcd binding and use of detectBindingResources
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/steps/etcdcluster.py
  test/acceptance/features/steps/etcdoperator.py
  test/acceptance/features/steps/nodejs_application.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/quarkus_application.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm, ok-to-test

#679 Fixed: owned resources are listed again in CSV
  Makefile
  deploy/crds/operators.coreos.com_v1alpha1_servicebinding_cr.yaml
  deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_operators_v1alpha1.go
  pkg/apis/operators/group.go
  pkg/apis/operators/v1alpha1/doc.go
  pkg/apis/operators/v1alpha1/register.go
  pkg/apis/operators/v1alpha1/servicebinding_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebinding/annotations.go
  pkg/controller/servicebinding/annotations_test.go
  pkg/controller/servicebinding/binder.go
  pkg/controller/servicebinding/binder_test.go
  pkg/controller/servicebinding/mapper.go
  pkg/controller/servicebinding/mapper_test.go
  pkg/controller/servicebinding/reconciler.go
  pkg/controller/servicebinding/reconciler_test.go
  pkg/controller/servicebinding/sbrcontroller.go
  pkg/controller/servicebinding/sbrcontroller_test.go
  pkg/controller/servicebinding/servicebinder.go
  pkg/controller/servicebinding/servicebinder_test.go
  pkg/controller/servicebinding/servicecontext.go
  pkg/controller/servicebinding/servicecontext_test.go
  test/e2e/servicebinding_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm

#675 [acceptance-tests] Make it possible to run SBO instance independendly on acceptnace testing setup.
  Makefile
  test/acceptance/features/steps/servicebindingoperator.py
Labels: approved, lgtm

#683 Check intermediate secret data contents in case of no application
  test/acceptance/features/bindAppToService.feature
Labels: approved, lgtm

#687 [acceptance-tests] Fix timeout waiting for serverless/knative to be imported
  test/acceptance/features/requirements.txt
  test/acceptance/features/steps/knative_serving.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/quarkus_application.py
  test/acceptance/features/steps/serverless_operator.py
Labels: approved, lgtm

#682 Remove obsolete e2e suite from repository
  CONTRIBUTING.md
  Makefile
  docs/ci.md
  docs/proposals/guidelines/proposal-template.md
  docs/pull_request_template.md
  hack/e2e-log-parser.sh
  hack/test-cleanup.sh
  test/e2e/main_test.go
  test/e2e/servicebinding_test.go
Labels: approved, lgtm

#685 Add test to cover binding using annotations on CRD
  test/acceptance/features/bindAppToService.feature
Labels: approved, lgtm

#689 [acceptance-tests] Add checks for feature files among linters.
  Makefile
  hack/check-feature-files.sh
Labels: approved, lgtm

#655 Add acceptance test for Service Binding Request with Custom Environment Variables
  test/acceptance/features/customEnvVar.feature
  test/acceptance/features/steps/app.py
  test/acceptance/features/steps/generic_testapp.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/steps.py
  test/acceptance/resources/apps/sbo-generic-test-app/Dockerfile
  test/acceptance/resources/apps/sbo-generic-test-app/conf/lighthttpd.conf
  test/acceptance/resources/apps/sbo-generic-test-app/env.sh
  test/acceptance/resources/apps/sbo-generic-test-app/start_http
Labels: approved, lgtm

#692 [acceptance-test] Bind two backend services by creating 1 SBR to a single application
  test/acceptance/features/bindAppToMultipleServices.feature
Labels: approved, lgtm
