Repository redhat-developer/service-binding-operator, pull requests merged in 2020-02, with the labels that each got.

#312 testing dev release
  Makefile
Labels: size/XS

#313 Add 10 mins sleep to dev-release target
  Makefile
Labels: size/XS

#293 pre-req refactor to support multiple backing services
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/plan_decoupled.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/related_resources.go
  pkg/controller/servicebindingrequest/retrieve_decoupled.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/mocks/fake.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#311 validation of olm bundles part1
  Makefile
  test/operator-hub/operator_source.yaml
  test/operator-hub/subscription.yaml
Labels: approved, lgtm, size/M

#318 oc is not installed in the openshift-ci in our cluster
  Makefile
Labels: approved, lgtm, size/XS

#316 update to a rhel8 base
  Dockerfile.rhel
Labels: approved, lgtm, size/XS

#320 OLM Bundle validation part2
  Makefile
  hack/dev-release.sh
Labels: approved, lgtm, size/M

#325 Update golang and operator-sdk version in OpenShift CI
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#326 Export all env variables
  Makefile
Labels: approved, lgtm, size/XS

#324 Enabled configuring of push-to-manifest-repo target using env variable
  Makefile
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
  deploy/olm-catalog/service-binding-operator/service-binding-operator.package.yaml
  hack/add-info-to-csv.go
  manifests/4.3/service-binding-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3/servicebindingrequests.apps.openshift.io.crd.yaml
  manifests/service-binding-operator.package.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L

#327 fix if case
  hack/dev-release.sh
Labels: approved, lgtm, size/XS

#328 added `createdAt`, `support`, `repository` annotations to improve UX on OperatorHub.io
  Makefile
  deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#329 Revert "Export all env variables (#326)"
  Makefile
Labels: approved, lgtm, size/XS

#330 Export all used environment variables
  Makefile
  hack/dev-release.sh
Labels: lgtm, size/XS

#332 Check for CSV existence
  hack/check-crds.sh
  hack/check-csvs.sh
  hack/dev-release.sh
Labels: lgtm, size/M

#335 Increase sleep interval for CSV check
  hack/check-csvs.sh
Labels: size/XS

#331 Update examples to use community version of the SBO.
  examples/commons.mk
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_postgresql/README.md
  hack/examples-commons.sh
Labels: approved, lgtm, size/M

#336 upgrade to sdk 0.15.2
  .travis.yml
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/usersetup.go
  vendor/github.com/operator-framework/operator-sdk/pkg/restmapper/dynamicrestmapper.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#337 Propagate Makefile failures to the travis.
  .travis.yml
Labels: approved, lgtm, size/XS

#338 Fix .travis.yaml
  .travis.yml
Labels: lgtm, size/XS

#340 Remove manifests from Dockerfile
  Dockerfile.rhel
Labels: approved, lgtm, size/XS

#322 Support multiple backing services
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  examples/multiple_services/README.md
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/bindinginfo_test.go
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
  pkg/controller/servicebindingrequest/plan_decoupled.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/retrieve_decoupled.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/e2e/empty.yaml
Labels: approved, lgtm, size/XXL

#339 Remove "Coming Soon"
  docs/OperatorBestPractices.md
Labels: approved, lgtm, size/XS

#341 Check CSV in default namespace
  hack/check-csvs.sh
Labels: approved, lgtm, size/XS

#342 Use default namespace for example CR
  hack/dev-release.sh
Labels: approved, lgtm, size/XS

#334 Refactor knative test: abridge test by removing unnecessary assertion.
  pkg/controller/servicebindingrequest/binder_test.go
Labels: approved, lgtm, size/S

#321 Replace BindingStatus field with Kubernetes compatible conditions
  examples/multiple_services/README.md
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/conditions/conditions.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/common.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/reconciler.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/_doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#345 Generate openapi for status.conditions
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/M

#349 remove unused funtion Retrieve()
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
Labels: approved, lgtm, size/M

#347 set version to 0.1.0
  Makefile
Labels: approved, lgtm, size/XS
