Repository redhat-developer/service-binding-operator, pull requests merged in 2020-12, with the labels that each got.

#770 Automate building of SBO bundle index images usable in CatalogSources on each merge to master
  .travis.yml
  Makefile
Labels: approved, lgtm

#604 Remove dead code related to relationship annotations
  pkg/controller/servicebinding/annotations.go
  pkg/controller/servicebinding/annotations_test.go
  pkg/controller/servicebinding/binder.go
  pkg/controller/servicebinding/binder_test.go
  pkg/controller/servicebinding/servicebinder.go
Labels: approved, lgtm, ok-to-test

#735 Support bindings injected as files in the application
  deploy/crds/operators.coreos.com_servicebindings_crd.yaml
  deploy/crds/operators.coreos.com_v1alpha1_servicebinding_cr.yaml
  deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
  docs/application-author.md
  pkg/apis/operators/v1alpha1/servicebinding_types.go
  pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebinding/binder.go
  pkg/controller/servicebinding/binder_test.go
  pkg/controller/servicebinding/retriever.go
  pkg/controller/servicebinding/retriever_test.go
  pkg/controller/servicebinding/servicebinder.go
  pkg/controller/servicebinding/servicebinder_test.go
  pkg/controller/servicebinding/servicecontext.go
  test/acceptance/features/injectBindingsAsFiles.feature
  test/acceptance/features/steps/app.py
  test/acceptance/features/steps/generic_testapp.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/service_binding.py
  test/mocks/mocks.go
Labels: approved, lgtm

#788 Improve regex to find yaml files
  Makefile
Labels: approved, lgtm

#787 Add acceptance test: Verify pulling data from a secret living in another namespace
  test/acceptance/features/bindAppToServiceUsingSecret.feature
Labels: approved, lgtm

#791 Set version to 0.4.0
  Makefile
Labels: approved, lgtm

#792 Step "Content of file in application pod" does not fail in case of connection errors
  test/acceptance/features/steps/generic_testapp.py
Labels: approved, lgtm

#793 run acceptance tests on Travis against the operator installed in the cluster
  .travis.yml
  hack/start-minikube.sh
  install.sh
Labels: approved, lgtm

#761 Add acceptance test for PodSpec path example
  .travis.yml
  examples/pod_spec_path/README.md
  test/acceptance/features/examples.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
Labels: approved, lgtm

#794 Add `prepare-operatorhub-pr` target
  Makefile
  hack/prepare-operatorhub-pr.sh
Labels: approved, do-not-merge/hold, lgtm

#795 Makefile GIT_COMMIT_ID length set to 8
  Makefile
Labels: approved, lgtm

#800 Simplify installation instructions
  README.md
Labels: approved, lgtm

#797 [acceptance tests] Create knative-serving namespace only if it does not exist
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#801 Stop pushing bundle metadata to additional manifest repo
  .travis.yml
Labels: approved, lgtm

#769 Refactor dev-release and validate-release jobs
  .travis.yml
  Makefile
  hack/check-operatorsource-pods.sh
  hack/deploy-sbo-local.sh
  hack/dev-release.sh
  hack/validate-release.sh
  install.sh
  test/acceptance/features/environment.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/servicebindingoperator.py
  test/operator-hub/operator_source.yaml
Labels: approved, lgtm

#802 Rename customEnvVar to mappings
  deploy/crds/operators.coreos.com_servicebindings_crd.yaml
  docs/application-author.md
  docs/binding-path.md
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_ibmcloud_operator/README.md
  examples/pod_spec_path/README.md
  pkg/apis/operators/v1alpha1/servicebinding_types.go
  pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/servicebinding/custom_env_parser.go
  pkg/controller/servicebinding/custom_env_parser_test.go
  pkg/controller/servicebinding/reconciler.go
  pkg/controller/servicebinding/retriever.go
  pkg/controller/servicebinding/retriever_test.go
  pkg/controller/servicebinding/service.go
  pkg/controller/servicebinding/service_test.go
  pkg/controller/servicebinding/servicebinder.go
  pkg/controller/servicebinding/servicebinder_test.go
  pkg/controller/servicebinding/servicecontext.go
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/customEnvVar.feature
  test/acceptance/features/injectBindingsAsFiles.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
  test/mocks/mocks.go
Labels: approved, lgtm

#621 Upgrade go version from 1.14 to 1.15
  .travis.yml
  Dockerfile.rhel
  go.mod
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#812 [acceptance-tests] Change catalog source for etcd operator to operatorhub.io
  test/acceptance/features/steps/etcdoperator.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm

#807 Fix Docker image pull limits
  Dockerfile.rhel
Labels: approved, lgtm

#814 Remove unused dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#803 Fix reading codecov.io token from CODECOV_TOKEN_PATH.
  .codecov.yaml
  .travis.yml
  Makefile
Labels: approved, lgtm

#820 Userguide
  docs/BackingServiceBestPractices.md
  docs/SBO User Guide.md
  docs/annotations.md
  docs/application-author.md
  docs/binding-path.md
Labels: approved, lgtm

#789 add a parameter max-concurrent-reconciles to set the reconile workers
  cmd/manager/main.go
  pkg/controller/servicebinding/controller.go
  pkg/controller/servicebinding/flag.go
Labels: approved, lgtm, needs-ok-to-test

#818 Take into account outputName in mapFromDataFieldDefinition (#817)
  pkg/controller/servicebinding/binding/definition.go
  pkg/controller/servicebinding/binding/definition_test.go
Labels: approved, lgtm, ok-to-test
