Repository redhat-developer/service-binding-operator, pull requests merged in 2020-03, with the labels that each got.

#360 Use visited paths as input for CustomEnvParser instead of processed environment variables
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/retrieve_decoupled.go
  pkg/controller/servicebindingrequest/secret.go
Labels: approved, lgtm, size/L

#357 Add example for using the Service Binding Operator with the IBM Cloud Operator
  assets/operator-hub-ibmcloudop-screenshot.png
  examples/nodejs_ibmcloud_operator/README.md
  examples/nodejs_ibmcloud_operator/language-translator-binding.yaml
  examples/nodejs_ibmcloud_operator/language-translator.yaml
  examples/nodejs_ibmcloud_operator/namespace.yaml
  examples/nodejs_ibmcloud_operator/service-binding-request.nodejs-app.yaml
Labels: approved, lgtm, ok-to-test, size/L

#362 Update readme to include IBM Cloud operator example
  README.md
Labels: approved, lgtm, size/XS

#363 Provide bound app's info in status as a GVK
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  go.mod
  go.sum
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm, size/L

#346 Support binding to a backing Service in a different namespace
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/bind_custom_resources.go
  pkg/controller/servicebindingrequest/binder_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/retriever.go
  pkg/controller/servicebindingrequest/retriever_test.go
  pkg/controller/servicebindingrequest/secret_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/fake.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/L

#369 Avoid appearance of empty fields
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binder.go
  pkg/controller/servicebindingrequest/binding_test.go
  pkg/controller/servicebindingrequest/planner.go
  pkg/controller/servicebindingrequest/planner_test.go
  pkg/controller/servicebindingrequest/sbrcontroller_test.go
  test/e2e/servicebindingrequest_test.go
  test/mocks/mocks.go
Labels: approved, lgtm, size/M

#370 Validate SBO releases
  Makefile
  hack/validate-release.sh
  test/operator-hub/subscription2.yaml
Labels: size/M

#371 (bug) Fix normalization of annotations to CRDDescription
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
Labels: approved, lgtm, size/M

#378 reverted version back to 0.1.0
  Makefile
Labels: approved, lgtm, size/XS

#350 Support creation of managed secret without associating it to a workload
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm, size/L

#359 Add test for conflicting resource ref and labels
  pkg/controller/servicebindingrequest/reconciler_test.go
Labels: approved, lgtm, size/M

#380 Add boilerplate file as operator-sdk generate open-api is deprecated
  hack/boilerplate.go.txt
Labels: approved, lgtm, size/S

#383 fix issue #377
  Makefile
Labels: approved, lgtm

#382 Remove osappsv1 from scheme
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#391 Include past releases in the bundle
  .travis.yml
  Makefile
  hack/dev-release.sh
  test/operator-hub/subscription.yaml
Labels: approved, lgtm

#393 Fix typo
  Makefile
Labels: lgtm

#395 Increment version to 0.1.1
  Makefile
Labels: approved, lgtm

#402 Check for install plan
  hack/check-installplan.sh
  hack/dev-release.sh
Labels: approved, lgtm

#379 Fix API rule violations
  deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
  pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.openapi.go
  pkg/controller/servicebindingrequest/binding.go
  pkg/controller/servicebindingrequest/reconciler_test.go
  pkg/controller/servicebindingrequest/secret.go
  pkg/controller/servicebindingrequest/secret_test.go
Labels: approved, lgtm, size/L

#397 Handle errors for CSV CRD does not installed
  pkg/controller/servicebindingrequest/olm.go
  pkg/controller/servicebindingrequest/olm_test.go
  pkg/controller/servicebindingrequest/sbrcontroller.go
Labels: approved, lgtm, ok-to-test
