Repository redhat-developer/service-binding-operator, pull requests merged in 2021-02, with the labels that each got.

#834 Fix ServiceBinding removal when service not exist
  controllers/reconciler.go
  test/acceptance/features/unbindAppToService.feature
Labels: approved, lgtm, ok-to-test

#849 Update roadmap link
  README.md
Labels: approved, lgtm

#867 Fix broken link to user guide
  README.md
Labels: approved, lgtm

#835 Add implementation to support flexible naming strategies to prepare binding names
  .gitignore
  README.md
  api/v1alpha1/servicebinding_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operators.coreos.com_servicebindings.yaml
  controllers/reconciler.go
  controllers/retriever.go
  controllers/retriever_test.go
  controllers/service.go
  controllers/service_test.go
  controllers/servicebinder.go
  controllers/servicecontext.go
  controllers/servicecontext_test.go
  docs/User_Guide.md
  examples/pod_spec_path/README.md
  examples/route_k8s_resource/README.md
  pkg/envvars/envvars.go
  pkg/envvars/envvars_test.go
  pkg/naming/naming.go
  pkg/naming/naming_test.go
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindWithCustomNamingStrategies.feature
  test/acceptance/features/deleteBackendServiceAndRecreate.feature
  test/acceptance/features/injectBindingsAsFiles.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
Labels: approved, lgtm

#865 Update API group to binding.operators.coreos.com
  PROJECT
  README.md
  api/v1alpha1/groupversion_info.go
  config/crd/bases/binding.operators.coreos.com_servicebindings.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_servicebindings.yaml
  config/crd/patches/webhook_in_servicebindings.yaml
  config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/servicebinding_editor_role.yaml
  config/rbac/servicebinding_viewer_role.yaml
  config/samples/operators_v1alpha1_servicebinding.yaml
  controllers/mapper_test.go
  controllers/secret_test.go
  controllers/servicebinder_test.go
  controllers/servicebinding_controller.go
  docs/User_Guide.md
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/multiple_services/README.md
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_etcd_operator/README.md
  examples/nodejs_ibmcloud_operator/README.md
  examples/nodejs_postgresql/README.md
  examples/nodejs_postgresql_namespaces/README.md
  examples/pod_spec_path/README.md
  examples/route_k8s_resource/README.md
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindAppToServiceAnnotations.feature
  test/acceptance/features/bindAppToServiceUsingConfigMap.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/bindWithCustomNamingStrategies.feature
  test/acceptance/features/customEnvVar.feature
  test/acceptance/features/deleteBackendServiceAndRecreate.feature
  test/acceptance/features/examples.feature
  test/acceptance/features/injectBindingsAsFiles.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
  test/acceptance/features/steps/service_binding.py
  test/acceptance/features/unbindAppToService.feature
  test/mocks/mocks.go
Labels: approved, lgtm

#870 Fix test-cleanup to use the generated CRD
  Makefile
  hack/remove-sbr-finalizers.sh
Labels: approved, lgtm

#877 Use ARTIFACT_DIR env var passed by Prow as test artifact location
  Makefile
Labels: approved, lgtm

#876 Starting 0.5.0 release cycle
  Makefile
Labels: approved, lgtm

#873 Service and application referenceable both using GVK and GVR
  api/v1alpha1/servicebinding_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/binding.operators.coreos.com_servicebindings.yaml
  config/manager/kustomization.yaml
  controllers/binder.go
  controllers/binder_test.go
  controllers/mapper.go
  controllers/mapper_test.go
  controllers/reconciler.go
  controllers/reconciler_test.go
  controllers/sbrcontroller.go
  controllers/sbrcontroller_test.go
  controllers/service.go
  controllers/service_test.go
  controllers/servicebinder.go
  controllers/servicebinder_test.go
  controllers/servicebinding_controller.go
  controllers/servicecontext.go
  controllers/servicecontext_test.go
  pkg/binding/spec.go
  pkg/binding/spec_test.go
  pkg/testutils/testutils.go
  test/acceptance/features/bindAppToServiceAnnotations.feature
  test/mocks/mocks.go
Labels: approved, lgtm

#875 Fix: use sourceKey to extract value from ConfigMap/Secret
  pkg/binding/model.go
  pkg/binding/spec_test.go
  test/acceptance/features/bindAppToServiceUsingConfigMap.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
Labels: approved, lgtm

#878 Fix: replace in user guide backingServiceSelectors/applicationSelector appearances with services/application
  docs/User_Guide.md
Labels: approved, lgtm, needs-ok-to-test

#806 Generating release.yaml
  .github/actions/setup-cli/action.yaml
  .github/actions/setup-cli/setup_tools.sh
  .github/workflows/pr-checks.yaml
  Makefile
  hack/check-python/requirements.txt
  hack/prepare-operatorhub-pr.sh
  hack/release-manifest.py
  test/acceptance/features/bindAppToServiceAnnotations.feature
  test/acceptance/features/bindAppToServiceUsingConfigMap.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
  test/acceptance/features/bindWithCustomNamingStrategies.feature
  test/acceptance/features/customEnvVar.feature
  test/acceptance/features/deleteBackendServiceAndRecreate.feature
  test/acceptance/features/examples.feature
  test/acceptance/features/injectBindingsAsFiles.feature
  test/acceptance/features/unbindAppToService.feature
Labels: approved, lgtm

#750 Immutable Binding Secrets
  controllers/binder.go
  controllers/binder_test.go
  controllers/common.go
  controllers/reconciler.go
  controllers/reconciler_test.go
  controllers/sbrcontroller.go
  controllers/secret.go
  controllers/secret/secret.go
  controllers/secret/secret_test.go
  controllers/secret_test.go
  controllers/service.go
  controllers/servicebinder.go
  controllers/servicebinder_test.go
  controllers/servicecontext_test.go
  docs/User_Guide.md
  examples/java_postgresql_customvar/README.md
  examples/knative_postgresql_customvar/README.md
  examples/multiple_services/README.md
  examples/nodejs_awsrds_varprefix/README.md
  examples/nodejs_postgresql/README.md
  examples/pod_spec_path/README.md
  examples/route_k8s_resource/README.md
  test/acceptance/features/bindAppToMultipleServices.feature
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindAppToServiceAnnotations.feature
  test/acceptance/features/bindKnativeService.feature
  test/acceptance/features/examples.feature
  test/acceptance/features/injectSecretAtCustomSchemaPath.feature
  test/acceptance/features/steps/generic_testapp.py
  test/acceptance/features/steps/steps.py
Labels: approved, lgtm
