Repository redhat-developer/service-binding-operator, pull requests merged in 2022-09, with the labels that each got.

#1208 Add merge-to-release-branch GH workflow
  .github/workflows/merge-to-release-branch.yaml
Labels: approved, lgtm, acceptance-tests-skipped

#1212 Bump Version 1.2.0
  antora-playbook.github.yaml
  antora-playbook.local.yaml
  make/version.mk
Labels: approved, lgtm, release/v1.2.x

#1214 Bump Version 1.2.0 (#1212)
  antora-playbook.github.yaml
  antora-playbook.local.yaml
  make/version.mk
Labels: approved, lgtm, cherry-pick, release/v1.2.x

#1195 Document labels used for issues
  CONTRIBUTING.md
Labels: approved, lgtm, acceptance-tests-skipped

#1215 Update operator manifests with spec v1beta1 resources
  config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Labels: approved, lgtm, release/v1.2.x

#1220 docs: difference between coreos & spec API
  docs/userguide/modules/binding-workloads-using-sbo/nav.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/api-differences.adoc
Labels: kind/documentation, approved, lgtm, acceptance-tests-skipped

#1219 docs: difference between coreos & spec API
  docs/userguide/modules/binding-workloads-using-sbo/nav.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/api-differences.adoc
Labels: kind/documentation, approved, lgtm, acceptance-tests-skipped

#1216 cherry-pick(release-v1.2.x): Update operator manifests with spec v1beta1
  config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Labels: approved, lgtm, cherry-pick, release/v1.2.x

#1222 Update chart directory with service binding operator 1.2.0
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/README.md
  charts/service-binding-operator/crds/clusterworkloadresourcemappings.servicebinding.io.yaml
  charts/service-binding-operator/crds/servicebindings.servicebinding.io.yaml
  charts/service-binding-operator/templates/clusterrole.yaml
  charts/service-binding-operator/templates/deployment.yaml
  charts/service-binding-operator/templates/tests/test-service-binding-operator-connection.yaml
  charts/service-binding-operator/values.schema.json
  charts/service-binding-operator/values.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.2.x

#1230 Fix result collecting script in performance test
  test/performance/collect-results.sh
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.1.x, release/v1.2.x

#1231 cherry-pick(release-v1.2.x): Fix result collecting script in performnace test
  test/performance/collect-results.sh
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.2.x

#1229 Ignore non-served crds in the crd controller
  controllers/crd/crd_controller.go
Labels: kind/bug, approved, lgtm

#1234 cherry-pick(release-v1.2.x): crds: Ignore non-served versions in crd controller
  controllers/crd/crd_controller.go
Labels: kind/bug, approved, lgtm, cherry-pick, release/v1.2.x

#1236 Bump vesion to 1.2.1
  make/version.mk
Labels: approved, lgtm

#1242 Add hack scripts for smoke-performance testing
  hack/perf/env.sh
  hack/perf/reset.sh
  hack/perf/run.sh
Labels: approved, lgtm, acceptance-tests-skipped

#1245 Tag OLM Descriptor related tests by @olm-descriptor tag
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
Labels: approved, lgtm
