Repository redhat-developer/service-binding-operator, pull requests merged in 2022-01, with the labels that each got.

#1080 Introduce sample application (spring-petclinic + postgresql) to be used in quickstart
  samples/apps/spring-petclinic/Dockerfile.app
  samples/apps/spring-petclinic/Makefile
  samples/apps/spring-petclinic/app-deployment.yaml
  samples/apps/spring-petclinic/db-deployment.yaml
  samples/apps/spring-petclinic/minikube/deploy-app.sh
  samples/apps/spring-petclinic/openshift/deploy-app.sh
  samples/apps/spring-petclinic/patch/pom.xml.patch
  samples/apps/spring-petclinic/service-binding.yaml
Labels: approved, lgtm

#1089 Upgrade cert manager from v1.1.0 to v1.6.0
  Makefile
Labels: approved, lgtm

#1090 Temporarily disable Cloud Native Postgres operator scenario for openshift 4.10
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm

#1091 Update contribution guide and pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/pull_request_template.md
Labels: approved, lgtm

#1092 Update obsoleted release instructions
  docs/community-release.md
  hack/prepare-operatorhub-pr.sh
Labels: kind/documentation, approved, lgtm

#1093 Avoid expression evaluation in the script
  hack/prepare-operatorhub-pr.sh
Labels: approved, lgtm

#1096 Use certified-operators catalog source for Crunchy Postgres Operator in acceptance tests
  test/acceptance/features/steps/crunchypostgresoperator.py
Labels: approved, lgtm, kind/test

#1095 Set channels to 'stable' for Operatorhub.io PR metadata
  Makefile
  hack/prepare-operatorhub-pr.sh
Labels: kind/enhancement, approved, lgtm
