Repository redhat-developer/service-binding-operator, pull requests merged in 2022-11, with the labels that each got.

#1297 Update versions of dependencies
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x

#1300 Remove v1beta1 CRD
  test/acceptance/features/discoverBindableResources.feature
  test/acceptance/resources/provisioned_backend_crdv1beta1.operator.manifest.yaml
Labels: approved, lgtm

#1296 Rebind workloads when their mappings change
  apis/common.go
  apis/spec/v1beta1/clusterworkloadresourcemapping_webhook.go
  apis/spec/v1beta1/clusterworkloadresourcemapping_webhook_test.go
  apis/webhooks/suite_test.go
  apis/webhooks/validator.go
  apis/webhooks/validator_test.go
  controllers/common.go
  main.go
  pkg/reconcile/pipeline/api.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/context/impl_test.go
  pkg/reconcile/pipeline/context/spec_binding_impl.go
  pkg/reconcile/pipeline/context/spec_binding_impl_test.go
  pkg/reconcile/pipeline/handler/mapping/impl.go
  pkg/reconcile/pipeline/handler/project/impl.go
  pkg/reconcile/pipeline/handler/project/impl_test.go
  pkg/reconcile/pipeline/mocks/mocks_pipeline.go
  test/acceptance/features/steps/app.py
  test/acceptance/features/workloadResourceMapping.feature
Labels: kind/enhancement, approved, lgtm

#1302 Bump version of Go to v1.18
  .github/workflows/merge-to-master.yaml
  .github/workflows/merge-to-release-branch.yaml
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks.yaml
  Dockerfile
  go.mod
  go.sum
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
Labels: kind/enhancement, approved, lgtm, release/v1.3.x

#1305 cherry-pick(release-v1.2.x): remove shruthihub as an owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.2.x

#1304 cherry-pick(release-v1.1.x): remove shruthihub as an owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.1.x, cherry-pick

#1306 cherry-pick(release-v1.3.x): remove shruthihub as an owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.3.x

#1270 Detect bindable resource based on status attribute
  pkg/reconcile/pipeline/context/service/crd_test.go
  pkg/reconcile/pipeline/context/service/service.go
  test/acceptance/resources/backend_crd.yaml
Labels: approved, lgtm

#1221 Test upgrade SBO with OLM
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks.yaml
  .gitignore
  hack/upgrade-sbo-env.sh
  make/acceptance.mk
  make/build.mk
  make/version.mk
  test/acceptance/features/environment.py
  test/acceptance/features/steps/environment.py
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/servicebindingoperator.py
  test/acceptance/features/steps/steps.py
  test/acceptance/features/steps/util.py
  test/acceptance/features/upgradeSBOwithOLM.feature
Labels: approved, lgtm

#1307 docs: Align docs branches to release branches
  antora-playbook.github.yaml
  antora-playbook.local.yaml
Labels: approved, lgtm, acceptance-tests-skipped

#1308 Create cluster-wide resources only once in performance test
  test/performance/run.sh
  test/performance/user-workloads/cluster-wide/sbo-test.yaml
  test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
Labels: approved, lgtm, acceptance-tests-skipped

#1309 Public DevGuide documentation update
  .gitignore
  antora-playbook.local.yaml.tmpl
  charts/service-binding-operator/templates/deployment.yaml
  charts/service-binding-operator/values.schema.json
  charts/service-binding-operator/values.yaml
  docs/devguide/antora.yml
  docs/devguide/modules/ROOT/pages/architecture.adoc
  docs/devguide/modules/acceptance-tests/nav.adoc
  docs/devguide/modules/acceptance-tests/pages/acceptance-tests.adoc
  docs/devguide/modules/install-sbo/nav.adoc
  docs/devguide/modules/install-sbo/pages/install-on-minikube.adoc
  docs/devguide/modules/install-sbo/pages/install-on-openshift.adoc
  docs/devguide/modules/install-sbo/partials/minikube/helm-install.adoc
  docs/devguide/modules/install-sbo/partials/minikube/manifests-install.adoc
  docs/devguide/modules/install-sbo/partials/minikube/olm-install.adoc
  docs/devguide/modules/install-sbo/partials/minikube/setup-minikube.adoc
  docs/devguide/modules/install-sbo/partials/olm-from-index.adoc
  docs/devguide/modules/install-sbo/partials/openshift/external-cr/helm-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/external-cr/manifests-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/external-cr/olm-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/external-cr/setup-openshift.adoc
  docs/devguide/modules/install-sbo/partials/openshift/internal-cr/helm-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/internal-cr/manifests-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/internal-cr/olm-install.adoc
  docs/devguide/modules/install-sbo/partials/openshift/internal-cr/setup-openshift.adoc
  docs/devguide/modules/install-sbo/partials/openshift/intro.adoc
  docs/devguide/modules/release-to-cr/nav.adoc
  docs/devguide/modules/release-to-cr/pages/release-to-cr.adoc
  hack/antora/partials/header-content.hbs
  install.sh
  make/build.mk
  make/docs.mk
Labels: kind/documentation, approved, lgtm
