Repository redhat-developer/service-binding-operator, pull requests merged in 2022-12, with the labels that each got.

#1311 Use community version of Percona MongoDB Operator in acceptance tests on OpenShift
  test/acceptance/features/steps/perconamongodboperator.py
Labels: approved, lgtm

#1312 cherry-pick(release-v1.3.x): Use community version of Percona MongoDB Operator in acceptance tests
  test/acceptance/features/steps/perconamongodboperator.py
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1310 Fix SBO checks for OpenShift 4.9
  test/acceptance/features/steps/servicebindingoperator.py
Labels: approved, lgtm

#1319 Bump version to v1.3.2
  make/version.mk
Labels: approved, lgtm, release/v1.3.x

#1321 bump version to v1.3.2 for helm chart
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x

#1317 Add list of supported workloads
  docs/userguide/modules/binding-workloads-using-sbo/pages/creating-service-binding.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/custom-path-injection.adoc
Labels: approved, lgtm, acceptance-tests-skipped

#1323 Add displayName and description to older versions of owned CRDs in CSV
  config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Labels: approved, lgtm, release/v1.3.x

#1329 Fix external link in devguide documentation
  docs/devguide/modules/install-sbo/partials/openshift/intro.adoc
Labels: kind/documentation, approved, lgtm, acceptance-tests-skipped

#1328 Update Crunchy Postgres Operator to v5.3.0 in acceptance tests
  .github/workflows/pr-checks.yaml
  samples/apps/spring-petclinic/pgcluster-deployment.yaml
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, release/v1.3.x

#1332 Include test/performance in Python linter
  hack/check-python/prepare-env.sh
  test/performance/kpidiff.py
Labels: kind/enhancement, approved, lgtm, acceptance-tests-skipped

#1334 Remove reconciler for spec v1alpha3 version
  controllers/spec/servicebinding_controller.go
  main.go
Labels: approved, lgtm

#1331 Adding support to upload performance kpi data to opensearch
  make/performance.mk
  test/performance/__init__.py
  test/performance/requirements.txt
  test/performance/upload_data.py
Labels: kind/enhancement, approved, lgtm, ok-to-test, acceptance-tests-skipped

#1330 Remove debug info from final binary
  make/build.mk
Labels: kind/enhancement, approved, lgtm
