Repository redhat-developer/service-binding-operator, pull requests merged in 2022-06, with the labels that each got.

#1159 docs: remove duplicate documentation directory
  docs/userguide/modules/creating-service-bindings/pages/binding-options.adoc
  docs/userguide/modules/creating-service-bindings/pages/creating-service-binding.adoc
  docs/userguide/modules/creating-service-bindings/pages/custom-path-injection.adoc
  docs/userguide/modules/creating-service-bindings/pages/unbind-application.adoc
Labels: kind/documentation, approved, lgtm

#1158 Fix generated filenames for controller role and rolebinding to follow naming convention in bundle
  make/build.mk
Labels: approved, lgtm

#1155 Add/Remove acceptance-tests-skipped label for PRs
  .github/actions/check-skip-acceptance-tests/action.yaml
  .github/workflows/pr-labels.yaml
Labels: kind/enhancement, approved, lgtm, ci

#1149 docs: fixups for label selection
  docs/userguide/modules/binding-workloads-using-sbo/pages/binding-options.adoc
Labels: kind/documentation, approved, lgtm

#1160 owners: add @shruthihub as approver & reviewer
  OWNERS
Labels: approved, lgtm

#1162 Bump version to v1.1.0
  antora-playbook.github.yaml
  antora-playbook.local.yaml
  make/version.mk
Labels: approved, lgtm

#1163 Add description and displayName to ClusterWorkloadResourceMapping in CSV
  config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1164 webhooks: validate workload resource mapping resources
  PROJECT
  apis/spec/v1alpha3/clusterworkloadresourcemapping_types.go
  apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook.go
  apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook_test.go
  config/crd/bases/binding.operators.coreos.com_bindablekinds.yaml
  config/crd/bases/binding.operators.coreos.com_servicebindings.yaml
  config/crd/bases/servicebinding.io_clusterworkloadresourcemappings.yaml
  config/crd/bases/servicebinding.io_servicebindings.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  main.go
  test/acceptance/features/steps/steps.py
  test/acceptance/features/workloadResourceMapping.feature
Labels: kind/enhancement, approved, lgtm

#1165 docs: use workload terminology for spec API
  docs/userguide/modules/binding-workloads-using-sbo/pages/creating-service-binding.adoc
  docs/userguide/modules/exposing-binding-data/pages/provisioned-service.adoc
Labels: kind/documentation, approved, lgtm, acceptance-tests-skipped

#1166 Change operator image baseimage to Red Hat's minima UBI 8
  Dockerfile
Labels: approved, lgtm, acceptance-tests-skipped

#1170 Bumped version for golang.org/x/text in order to fix security vulnerability
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: approved, lgtm

#1171 Add GH action for security scan.
  .github/workflows/merge-to-master.yaml
  .github/workflows/pr-checks.yaml
  make/version.mk
Labels: approved, lgtm, ci

#1174 Print subject access review error to logs.
  pkg/reconcile/pipeline/context/impl.go
Labels: kind/enhancement, approved, lgtm

#1177 Update chart with sbo 1.1.1 app version
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/clusterrole.yaml
  charts/service-binding-operator/templates/clusterrolebinding.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped

#1178 Ignore security warnings without known fixes
  .github/workflows/merge-to-master.yaml
  .github/workflows/pr-checks.yaml
Labels: approved, lgtm

#1179 Change quay.io/redhat-developer/servicebinding-operator:index image to file-based catalog
  .github/actions/setup-podman/opm
  .github/workflows/pr-checks-build-images.yaml
  make/build.mk
  make/common.mk
Labels: kind/bug, approved, lgtm, ci
