Repository redhat-developer/service-binding-operator, pull requests merged in 2022-04, with the labels that each got.

#1121 Add instruction to run tests
  CONTRIBUTING.md
Labels: lgtm

#1127 Fix CI
  .github/workflows/pr-checks.yaml
  Makefile
  hack/common.mk
  pkg/naming/naming.go
  pkg/reconcile/pipeline/context/service/service_test.go
Labels: kind/bug, approved, lgtm

#1128 Update additional resources:Added Service Binding Operator Blog and Drag&Drop JAR and Service Binding
  README.md
Labels: approved, lgtm

#1129 Upgrade codecov-action from deprecated v1 to v3
  .github/workflows/pr-checks.yaml
Labels: kind/enhancement, lgtm, ci

#1086 Workload resource mapping
  apis/spec/v1alpha3/cluster_workload_resource_mapping.go
  apis/spec/v1alpha3/groupversion_info.go
  apis/spec/v1alpha3/servicebinding_webhook.go
  apis/spec/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/servicebinding.io_clusterworkloadresourcemappings.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/common.go
  pkg/converter/unstructured.go
  pkg/converter/unstructured_test.go
  pkg/reconcile/pipeline/api.go
  pkg/reconcile/pipeline/builder/pipeline_integration_test.go
  pkg/reconcile/pipeline/context/application.go
  pkg/reconcile/pipeline/context/application_test.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/context/impl_test.go
  pkg/reconcile/pipeline/context/spec_binding_impl.go
  pkg/reconcile/pipeline/context/spec_binding_impl_test.go
  pkg/reconcile/pipeline/handler/project/impl.go
  pkg/reconcile/pipeline/handler/project/impl_test.go
  pkg/reconcile/pipeline/mapping.go
  pkg/reconcile/pipeline/mapping_test.go
  pkg/reconcile/pipeline/mocks/mocks_pipeline.go
  test/acceptance/features/steps/steps.py
  test/acceptance/features/workloadResourceMapping.feature
  test/acceptance/resources/custom_app.operator.manifest.yaml
  test/acceptance/resources/not_a_pod.operator.manifest.yaml
Labels: lgtm

#1133 Upgrade codecov-action from deprecated v1 to v3 for merge-to-master
  .github/workflows/merge-to-master.yaml
Labels: kind/bug, ci

#1134 Pin Crunchy PostgreSQL Operator version to v5.0.5 for acceptance tests with Minikube
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
Labels: kind/bug, approved, lgtm, kind/test

#1131 Create non-admin user for acceptance tests for OpenShift only if it does not exist
  test/acceptance/openshift-setup.sh
Labels: approved, lgtm

#1136 Fix 'Service Binding is ready' step assertions
  test/acceptance/features/steps/service_binding.py
Labels: kind/bug, approved, lgtm, kind/test
