Repository redhat-developer/service-binding-operator, pull requests merged in 2022-05, with the labels that each got.

#1137 Updating the readme file with the link to the latest blog on SBO
  README.md
Labels: approved, lgtm

#1125 Add missing manifest and make targets for MySQL Cluster Sample
  samples/apps/spring-petclinic/Makefile
  samples/apps/spring-petclinic/petclinic-mysqlcluster-binding.yaml
Labels: approved, lgtm, ok-to-test

#1138 Add performance testing framework
  Makefile
  test/performance/.gitignore
  test/performance/collect-kpi.sh
  test/performance/collect-metrics.sh
  test/performance/collect-results.sh
  test/performance/deploy-sbr.sh
  test/performance/install-operators.sh
  test/performance/kpi.py
  test/performance/kpidiff.py
  test/performance/run.sh
  test/performance/setup.sh
  test/performance/user-workloads/incomplete/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.sbr.yaml
  test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.sbr.yaml
  test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
Labels: kind/enhancement, approved, lgtm, kind/test, ci

#1130 bind labeled workloads created after sb reconcile
  controllers/common.go
  docs/userguide/modules/creating-service-bindings/pages/binding-options.adoc
  go.mod
  main.go
  pkg/reconcile/pipeline/api.go
  pkg/reconcile/pipeline/builder/pipeline.go
  pkg/reconcile/pipeline/builder/pipeline_integration_test.go
  pkg/reconcile/pipeline/builder/pipeline_test.go
  pkg/reconcile/pipeline/context/flow_ctrl.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/context/impl_test.go
  pkg/reconcile/pipeline/context/spec_binding_impl.go
  pkg/reconcile/pipeline/context/spec_binding_impl_test.go
  pkg/reconcile/pipeline/handler/project/impl.go
  pkg/reconcile/pipeline/handler/project/impl_test.go
  pkg/reconcile/pipeline/mapping.go
  pkg/reconcile/pipeline/mapping_test.go
  pkg/reconcile/pipeline/mocks/mocks_pipeline.go
  test/acceptance/features/bindMultipleAppsToSingleService.feature
  test/acceptance/features/steps/generic_testapp.py
  test/acceptance/features/steps/steps.py
  vendor/modules.txt
Labels: kind/enhancement, approved, lgtm

#1143 Install pre-built latest version of sandbox for the performance test.
  test/performance/setup.sh
Labels: kind/enhancement, approved, lgtm, kind/test, ci

#1144 docs: publish different version of the docs
  Makefile
  antora-playbook.yaml
Labels: kind/documentation, approved, lgtm, ok-to-test

#1132 Service Binding Operator Helm chart
  charts/service-binding-operator/.helmignore
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/LICENSE.md
  charts/service-binding-operator/README.md
  charts/service-binding-operator/crds/bindablekinds.binding.operators.coreos.com.yaml
  charts/service-binding-operator/crds/servicebindings.binding.operators.coreos.com.yaml
  charts/service-binding-operator/crds/servicebindings.servicebinding.io.yaml
  charts/service-binding-operator/templates/_helpers.tpl
  charts/service-binding-operator/templates/certificate.yaml
  charts/service-binding-operator/templates/clusterrole.yaml
  charts/service-binding-operator/templates/clusterrolebinding.yaml
  charts/service-binding-operator/templates/configMap.yaml
  charts/service-binding-operator/templates/deployment.yaml
  charts/service-binding-operator/templates/issuer.yaml
  charts/service-binding-operator/templates/role.yaml
  charts/service-binding-operator/templates/rolebinding.yaml
  charts/service-binding-operator/templates/service-account.yaml
  charts/service-binding-operator/templates/service.yaml
  charts/service-binding-operator/templates/tests/test-service-binding-operator-connection.yaml
  charts/service-binding-operator/templates/webhook.yaml
  charts/service-binding-operator/values.schema.json
  charts/service-binding-operator/values.yaml
  docs/userguide/modules/getting-started/pages/installing-service-binding.adoc
  test/charts/service-binding-operator/Dockerfile
  test/charts/service-binding-operator/application.yaml
  test/charts/service-binding-operator/sbo.yaml
  test/charts/service-binding-operator/secret.yaml
  test/charts/service-binding-operator/test-entrypoint.sh
Labels: approved, lgtm

#1145 Enable site generation using GitHub sources to enable multi-version docs in gh-pages
  .github/workflows/merge-to-master.yaml
  Makefile
  antora-playbook.github.yaml
  antora-playbook.local.yaml
Labels: kind/documentation, kind/enhancement, approved, lgtm, ci

#1148 Re-organize Makefile into smaller managable pieces
  Makefile
  make/acceptance.mk
  make/build.mk
  make/common.mk
  make/deploy.mk
  make/docs.mk
  make/lint.mk
  make/performance.mk
  make/release.mk
  make/test.mk
  make/version.mk
Labels: kind/enhancement, approved, lgtm

#1142 Updates to upstream to sync with downstream content
  config/rbac/percona_mongodb_clusterrole.yaml
  docs/userguide/antora.yml
  docs/userguide/modules/ROOT/pages/intro.adoc
  docs/userguide/modules/binding-workloads-using-sbo/nav.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/binding-options.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/creating-service-binding.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/custom-path-injection.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/unbinding-workloads.adoc
  docs/userguide/modules/exposing-binding-data/nav.adoc
  docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc
  docs/userguide/modules/exposing-binding-data/pages/detect-bindings.adoc
  docs/userguide/modules/exposing-binding-data/pages/direct-secret-reference.adoc
  docs/userguide/modules/exposing-binding-data/pages/intro-expose-binding.adoc
  docs/userguide/modules/exposing-binding-data/pages/olm-descriptors.adoc
  docs/userguide/modules/exposing-binding-data/pages/provisioned-service.adoc
  docs/userguide/modules/exposing-binding-data/pages/rbac-requirements.adoc
  docs/userguide/modules/getting-started/nav.adoc
  docs/userguide/modules/getting-started/pages/installing-service-binding.adoc
  docs/userguide/modules/getting-started/pages/petclinic-pgcluster.adoc
  docs/userguide/modules/getting-started/pages/petclinic-postgresql.adoc
  docs/userguide/modules/getting-started/pages/quick-start.adoc
  docs/userguide/modules/getting-started/partials/common-prerequisities.adoc
  docs/userguide/modules/getting-started/partials/connecting-petclinic-db.adoc
  docs/userguide/modules/getting-started/partials/creating-db-pgcluster.adoc
  docs/userguide/modules/getting-started/partials/creating-db-postgresql.adoc
  docs/userguide/modules/getting-started/partials/deploying-application.adoc
  docs/userguide/modules/getting-started/partials/introduction.adoc
  docs/userguide/modules/getting-started/partials/next-steps.adoc
  docs/userguide/modules/getting-started/partials/petclinic-db.adoc
  docs/userguide/modules/getting-started/partials/scenario-diagram-description-pgcluster.adoc
  docs/userguide/modules/getting-started/partials/scenario-diagram-description-postgresql.adoc
  docs/userguide/modules/projecting-binding-data/nav.adoc
  docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
Labels: kind/documentation, approved, lgtm

#1150 Skip running acceptance tests in GH workflows for PR that does not change SBO nor the testing framework
  .github/actions/check-skip-acceptance-tests/action.yaml
  .github/workflows/pr-checks.yaml
Labels: kind/enhancement, approved, lgtm, kind/test, ci

#1152 Update CI docs.
  docs/ci.md
Labels: kind/documentation, approved, lgtm

#1154 Add SBO icon to chart metadata
  charts/service-binding-operator/Chart.yaml
Labels: approved, lgtm

#1153 Add support for servicebinding.io API for performance testing
  test/performance/collect-kpi.sh
  test/performance/collect-results.sh
  test/performance/deploy-sbr.sh
  test/performance/kpi.py
  test/performance/kpidiff.py
  test/performance/run.sh
  test/performance/user-workloads/incomplete/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.sbr.spec.yaml
  test/performance/user-workloads/invalid/sbo-test.sbr.yaml
  test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.sbr.spec.yaml
  test/performance/user-workloads/valid/sbo-test.sbr.yaml
  test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
Labels: kind/enhancement, approved, lgtm, kind/test
