Repository redhat-developer/service-binding-operator, pull requests merged in 2022-10, with the labels that each got.

#1246 cherry-pick(release-v1.2.x): Add hack scripts for smoke-performance testing.
  hack/perf/env.sh
  hack/perf/reset.sh
  hack/perf/run.sh
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.2.x

#1248 Fix typos in documentation
  CONTRIBUTING.md
  README.md
Labels: kind/documentation, approved, lgtm, acceptance-tests-skipped

#1249 Add filariow as an owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped

#1247 cherry-pick(release-v1.2.x): Tag OLM Descriptor related tests by @olm-descriptor tag
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
Labels: approved, lgtm, cherry-pick, release/v1.2.x

#1253 cherry-pick(release-v1.3.x): Ensure the desired install plan is approved in acceptance tests
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1251 disable olm descriptor support
  docs/userguide/modules/ROOT/pages/intro.adoc
  docs/userguide/modules/binding-workloads-using-sbo/pages/binding-options.adoc
  docs/userguide/modules/exposing-binding-data/nav.adoc
  docs/userguide/modules/exposing-binding-data/pages/intro-expose-binding.adoc
  docs/userguide/modules/exposing-binding-data/pages/olm-descriptors.adoc
  pkg/reconcile/pipeline/api.go
  pkg/reconcile/pipeline/context/service/crd_test.go
  pkg/reconcile/pipeline/context/service/service.go
  pkg/reconcile/pipeline/handler/collect/impl.go
  pkg/reconcile/pipeline/handler/collect/impl_test.go
  pkg/reconcile/pipeline/mocks/mocks_pipeline.go
  test/acceptance/features/bindAppToService.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
  test/acceptance/resources/backend-new-spec.operator.manifest.yaml
  test/acceptance/resources/backends_bar.operator.manifest.yaml
  test/acceptance/resources/backends_foo.operator.manifest.yaml
Labels: kind/enhancement, approved, lgtm, release/v1.3.x

#1257 cherry-pick(release-v1.3.x): Bump version to v1.3.0
  antora-playbook.github.yaml
  antora-playbook.local.yaml
  make/version.mk
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1252 cherry-pick(release-v1.2.x): Ensure the desired install plan is approved in acceptance tests
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, cherry-pick, release/v1.2.x

#1255 Bump version to v1.3.0
  antora-playbook.github.yaml
  antora-playbook.local.yaml
  make/version.mk
Labels: lgtm, release/v1.3.x

#1258 update chart with service binding operator 1.3.0
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x

#1261 cherry-pick(release-v1.3.x): update chart with 1.3.0
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.3.x

#1264 cherry-pick(release-v1.3.x): Fix or temporarily disable tests for supported operators that does not currently work with OCP 4.12
  .github/workflows/pr-checks.yaml
  samples/apps/spring-petclinic/pgcluster-deployment.yaml
  test/acceptance/features/gettingStartedGuide.feature
  test/acceptance/features/steps/cloudnativepostgresoperator.py
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1263 cherry-pick(release-v1.2.x): Fix or temporarily disable tests for supported operators that does not currently work with OCP 4.12
  .github/workflows/pr-checks.yaml
  samples/apps/spring-petclinic/pgcluster-deployment.yaml
  test/acceptance/features/gettingStartedGuide.feature
  test/acceptance/features/steps/cloudnativepostgresoperator.py
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, cherry-pick, release/v1.2.x

#1260 Remove duplicate scenario
  test/acceptance/features/supportSpecBeta1Resources.feature
Labels: approved, lgtm, release/v1.2.x, release/v1.3.x

#1265 cherry-pick(release-v1.3.x): Remove duplicate scenario
  test/acceptance/features/supportSpecBeta1Resources.feature
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1217 Add GH workflows for cherry-picking PRs to release branches
  .github/workflows/pr-cherry-pick-clean.yaml
  .github/workflows/pr-cherry-picks.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.1.x, release/v1.2.x, release/v1.3.x

#1273 remove shruthihub as an owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped

#1271 Compare various KPIs to the threshold values and fail if any is crossed
  make/common.mk
  make/performance.mk
Labels: approved, lgtm, release/v1.3.x

#1275 Bump version of Go to v1.18
  .github/actions/setup-cli/action.yaml
  .github/workflows/merge-to-master.yaml
  .github/workflows/merge-to-release-branch.yaml
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks.yaml
  Dockerfile
  go.mod
  go.sum
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: approved, lgtm

#1278 Revert "Bump version of Go to v1.18 and fix CVE-2022-32149"
  .github/actions/setup-cli/action.yaml
  .github/workflows/merge-to-master.yaml
  .github/workflows/merge-to-release-branch.yaml
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks.yaml
  Dockerfile
  go.mod
  go.sum
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: approved, lgtm

#1279 Fix CVE-2022-32149
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: approved, lgtm, release/v1.3.x

#1282 Bump version to v1.3.1
  make/version.mk
Labels: approved, lgtm, release/v1.3.x

#1274 Stop using deprecated features in GH actions
  .github/actions/check-skip-acceptance-tests/action.yaml
  .github/workflows/merge-to-master.yaml
  .github/workflows/merge-to-release-branch.yaml
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks-clean-images.yaml
  .github/workflows/pr-checks-push-images.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-cherry-picks.yaml
  .github/workflows/pr-labels.yaml
Labels: approved, lgtm, release/v1.1.x, release/v1.2.x, release/v1.3.x

#1280 Add install-tools and local-env rules to Makefiles
  CONTRIBUTING.md
  make/acceptance.mk
  make/build.mk
  make/common.mk
  make/deploy.mk
Labels: kind/enhancement, approved, lgtm, release/v1.2.x, release/v1.3.x

#1284 Fix Percona MongoDB operator support
  README.md
  pkg/binding/registry/registry.go
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, release/v1.2.x, release/v1.3.x

#1293 Fix deploy/uninstall rule
  make/deploy.mk
Labels: kind/bug, approved, lgtm, acceptance-tests-skipped

#1292 bump SBO helm chart to v1.3.1
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x
