Repository redhat-developer/service-binding-operator, pull requests merged in 2022-02, with the labels that each got.

#1085 Refactor getting started guide to use the sample spring-petclinic
  docs/userguide/antora.yml
  docs/userguide/modules/exposing-binding-data/nav.adoc
  docs/userguide/modules/getting-started/assets/attachments/app-deployment.yaml
  docs/userguide/modules/getting-started/assets/attachments/init-database.sh
  docs/userguide/modules/getting-started/assets/attachments/petclinic-deployment.yaml
  docs/userguide/modules/getting-started/assets/attachments/petclinic-pgcluster-binding.yaml
  docs/userguide/modules/getting-started/assets/attachments/petclinic-postgresql-binding.yaml
  docs/userguide/modules/getting-started/assets/attachments/pgcluster-deployment.yaml
  docs/userguide/modules/getting-started/assets/attachments/postgresql-deployment.yaml
  docs/userguide/modules/getting-started/assets/attachments/service-binding.yaml
  docs/userguide/modules/getting-started/assets/images/pgcluster-spring-boot.png
  docs/userguide/modules/getting-started/assets/images/postgresql-spring-boot.png
  docs/userguide/modules/getting-started/nav.adoc
  docs/userguide/modules/getting-started/pages/petclinic-pgcluster.adoc
  docs/userguide/modules/getting-started/pages/petclinic-postgresql.adoc
  docs/userguide/modules/getting-started/pages/quick-start.adoc
  docs/userguide/modules/getting-started/partials/common-prerequisities.adoc
  docs/userguide/modules/getting-started/partials/connecting-petclinic-db.adoc
  docs/userguide/modules/getting-started/partials/creating-db-pgcluster.adoc
  docs/userguide/modules/getting-started/partials/creating-db-postgresql.adoc
  docs/userguide/modules/getting-started/partials/deploying-application.adoc
  docs/userguide/modules/getting-started/partials/introduction.adoc
  docs/userguide/modules/getting-started/partials/next-steps.adoc
  docs/userguide/modules/getting-started/partials/petclinic-db.adoc
  docs/userguide/modules/getting-started/partials/scenario-diagram-description-pgcluster.adoc
  docs/userguide/modules/getting-started/partials/scenario-diagram-description-postgresql.adoc
  samples/apps/spring-petclinic/Makefile
  samples/apps/spring-petclinic/minikube/deploy-app.sh
  samples/apps/spring-petclinic/openshift/deploy-app.sh
  samples/apps/spring-petclinic/petclinic-deployment.yaml
  samples/apps/spring-petclinic/petclinic-pgcluster-binding.yaml
  samples/apps/spring-petclinic/petclinic-postgresql-binding.yaml
  samples/apps/spring-petclinic/pgcluster-deployment.yaml
  samples/apps/spring-petclinic/postgresql-deployment.yaml
  test/acceptance/features/gettingStartedGuide.feature
  test/acceptance/features/steps/getting_started.py
  test/acceptance/features/steps/service_binding.py
Labels: kind/documentation, approved, lgtm

#1099 Fix operator-sdk version in merge-to-master GH action
  .github/workflows/merge-to-master.yaml
Labels: kind/bug, approved, lgtm

#1101 Switch log format back to JSON
  Dockerfile
  config/manager/manager.yaml
  pkg/log/log.go
Labels: approved, lgtm

#1100 Remove unused CRDs and mock objects
  test/acceptance/features/steps/dboperator.py
  test/acceptance/features/steps/etcdcluster.py
  test/acceptance/features/steps/etcdoperator.py
  test/acceptance/features/steps/postgres_db.py
  test/acceptance/features/steps/steps.py
  test/mocks/fake.go
  test/mocks/mocks.go
  test/third-party-crds/etcd_v1beta2_etcdcluster_crd.yaml
  test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
Labels: approved, lgtm

#1105 Fix Percona XtraDB Cluster (mysql) annotations
  pkg/binding/registry/registry.go
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: kind/bug, approved, lgtm

#1108 Include pod logs while collecting kube resources in GitHub actions
  .github/actions/collect-kube-resources/action.yaml
Labels: approved, lgtm, ci

#1104 Bump version to v1.0.1
  Makefile
Labels: approved, lgtm

#1107 Added Spring Petclinic Application Deployment yaml compatible with MySQL and custom resource yaml for creating instance of PerconaXtraDB cluster
  samples/apps/spring-petclinic/mysqlcluster-deployment.yaml
  samples/apps/spring-petclinic/petclinic-mysql-deployment.yaml
Labels: approved, lgtm
