Repository redhat-developer/service-binding-operator, pull requests merged in 2022-08, with the labels that each got.

#1193 Extend the acceptance testing framework to support installing operator with both manual and automatic subscriptions
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/subscription_install_mode.py
Labels: kind/enhancement, approved, lgtm

#1191 Add docs to set permissions due to Kubernetes bug
  docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
Labels: approved, lgtm, acceptance-tests-skipped

#1196 Correct asciidoc syntax for link
  docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
Labels: acceptance-tests-skipped

#1198 Tweak golangci-lint to avoid out-of-memory in Github Actions
  go.sum
  make/lint.mk
  pkg/client/kubernetes/whoami.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/context/spec_binding_impl.go
Labels: approved, lgtm, ci

#1200 Update DCO to align with redhat-developer organization guidelines.
  CONTRIBUTING.md
  DCO
Labels: approved, lgtm, acceptance-tests-skipped

#1199 Fix hidden dependency between scenarios in acceptance tests
  test/acceptance/features/steps/cloudnativepostgresoperator.py
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/percona_mysql_operator.py
  test/acceptance/features/steps/perconamongodboperator.py
  test/acceptance/features/steps/rabbitmq_operator.py
  test/acceptance/features/steps/redisoperator.py
  test/acceptance/features/steps/serverless_operator.py
Labels: approved, lgtm

#1203 Upgrade cert-manager release to v1.9.1
  make/deploy.mk
Labels: approved, lgtm, acceptance-tests-skipped

#1204 Update Crunchy postgres operator version to v5.1.2
  docs/userguide/modules/getting-started/partials/creating-db-pgcluster.adoc
  samples/apps/spring-petclinic/pgcluster-deployment.yaml
  test/acceptance/features/steps/command.py
  test/acceptance/features/steps/crunchypostgresoperator.py
  test/acceptance/features/steps/getting_started.py
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: kind/documentation, approved, lgtm

#1197 Document rebind behavior
  docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
Labels: acceptance-tests-skipped

#1207 Use fewer pod replicas in testing deployments
  test/acceptance/features/steps/openshift.py
Labels: kind/bug, approved, lgtm

#1206 Expose binding secret without requiring a workload
  pkg/reconcile/pipeline/api.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/context/impl_test.go
  pkg/reconcile/pipeline/context/spec_binding_impl_test.go
  pkg/reconcile/pipeline/handler/project/impl.go
  pkg/reconcile/pipeline/handler/project/impl_test.go
  pkg/reconcile/pipeline/mocks/mocks_pipeline.go
  test/acceptance/features/bindAppToServiceAnnotations.feature
  test/acceptance/features/bindAppToServiceUsingSecret.feature
Labels: kind/enhancement, approved, lgtm

#1192 Delete namespace after every scenario
  test/acceptance/features/environment.py
Labels: kind/enhancement, approved, lgtm

#1209 Enable PR checks on release branches
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks-clean-images.yaml
  .github/workflows/pr-checks-push-images.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-labels.yaml
Labels: approved, lgtm

#1210 cherry-pick(release-v1.1.x): Enable PR checks on release branches
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks-clean-images.yaml
  .github/workflows/pr-checks-push-images.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-labels.yaml
Labels: approved, lgtm, release/v1.1.x, cherry-pick
