Repository redhat-developer/service-binding-operator, pull requests merged in 2023-02, with the labels that each got.

#1385 Fix CVE-2022-28948
  go.mod
  go.sum
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, priority/high

#1386 fix(release-v1.3.x): Fix CVE-2022-28948
  go.mod
  go.sum
  test/_projects/api-client/go.mod
  test/_projects/api-controller/go.mod
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, priority/high, release/v1.3.x

#1387 Add daily workflow to check for security vulnerabilities regularly
  .github/workflows/periodic-security-check.yaml
Labels: approved, lgtm, acceptance-tests-skipped

#1390 bump to version v1.3.4
  make/version.mk
Labels: approved, lgtm, release/v1.3.x

#1391 Remove @jasperchui as owner
  OWNERS
Labels: approved, lgtm, acceptance-tests-skipped
