Repository redhat-developer/service-binding-operator, pull requests merged in 2023-01, with the labels that each got.

#1327 Add dependabot configuration
  .github/dependabot.yml
Labels: approved, lgtm, acceptance-tests-skipped

#1335 Fixed the environment issue in CI
  make/performance.mk
Labels: kind/enhancement, approved, lgtm, needs-ok-to-test, acceptance-tests-skipped

#1325 add gosec security checks
  .github/workflows/pr-checks.yaml
  apis/webhooks/validator.go
  pkg/reconcile/pipeline/context/impl.go
  pkg/reconcile/pipeline/mapping.go
  test/_projects/api-controller/main.go
Labels: approved, lgtm, kind/test

#1359 cherry-pick(release-v1.3.x): Test upgrade SBO with OLM
  .github/workflows/pr-checks-build-images.yaml
  .github/workflows/pr-checks.yaml
  .gitignore
  hack/upgrade-sbo-env.sh
  make/acceptance.mk
  make/build.mk
  make/version.mk
  test/acceptance/features/environment.py
  test/acceptance/features/steps/environment.py
  test/acceptance/features/steps/olm.py
  test/acceptance/features/steps/openshift.py
  test/acceptance/features/steps/servicebindingoperator.py
  test/acceptance/features/steps/steps.py
  test/acceptance/features/steps/util.py
  test/acceptance/features/upgradeSBOwithOLM.feature
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1358 cherry-pick(release-v1.3.x): Remove v1beta1 CRD
  test/acceptance/features/discoverBindableResources.feature
  test/acceptance/resources/provisioned_backend_crdv1beta1.operator.manifest.yaml
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1357 cherry-pick(release-v1.3.x): Detect bindable resource based on status attribute
  pkg/reconcile/pipeline/context/service/crd_test.go
  pkg/reconcile/pipeline/context/service/service.go
  test/acceptance/resources/backend_crd.yaml
Labels: approved, lgtm, cherry-pick, release/v1.3.x

#1360 Bump version to v1.3.3
  make/version.mk
Labels: approved, lgtm, release/v1.3.x

#1364 Bump version to v1.3.3 for helm chart
  charts/service-binding-operator/Chart.yaml
  charts/service-binding-operator/templates/deployment.yaml
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x

#1363 Added metadata with performance kpi data upload
  test/performance/collect-kpi.sh
  test/performance/upload_data.py
Labels: kind/enhancement, approved, lgtm, needs-ok-to-test, acceptance-tests-skipped

#1372 cherry-pick(release-v1.3.x): #1331, #1335 and #1363 for latest changes in the performance test
  make/performance.mk
  test/performance/__init__.py
  test/performance/collect-kpi.sh
  test/performance/requirements.txt
  test/performance/upload_data.py
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.3.x

#1373 cherry-pick(release-v1.3.x): Create cluster-wide resources only once in performance test (#1308)
  test/performance/run.sh
  test/performance/user-workloads/cluster-wide/sbo-test.yaml
  test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml
  test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
Labels: approved, lgtm, acceptance-tests-skipped, cherry-pick, release/v1.3.x

#1374 Disable scenarios not supported for OCP v4.12 also for OCP v4.13
  test/acceptance/features/gettingStartedGuide.feature
  test/acceptance/features/supportExistingOperatorBackedServices.feature
Labels: approved, lgtm, release/v1.3.x

#1376 Fixed the type of execution_timestamp
  test/performance/upload_data.py
Labels: approved, lgtm, needs-ok-to-test, acceptance-tests-skipped, release/v1.3.x

#1378 Bump opensearch-py to v2.1.1
  test/performance/requirements.txt
  test/performance/upload_data.py
Labels: approved, lgtm, acceptance-tests-skipped, release/v1.3.x
