Repository redhat-developer/service-binding-operator, pull requests merged in 2023-08, with the labels that each got.

#1466 Add polling to App.get_generation in tests
  test/acceptance/features/steps/app.py
Labels: approved, lgtm

#1467 ci: bump python version to 3.11
  .github/workflows/merge-to-master.yaml
  .github/workflows/pr-checks.yaml
Labels: approved, lgtm, kind/test

#1471 test: change oc's --docker-image flag to --image
  test/acceptance/features/steps/openshift.py
Labels: kind/bug, approved, lgtm, release/v1.3.x

#1470 test: disable deployment configs in openshift 4.14
  test/acceptance/features/bindAppToProvisionedService.feature
Labels: kind/bug, approved, lgtm, release/v1.3.x

#1476 bump version to v1.4.0
  make/version.mk
Labels: kind/enhancement, approved, lgtm

#1481 add cherry pick action for v1.4.x release branch
  .github/workflows/pr-cherry-picks.yaml
Labels: kind/enhancement, approved, lgtm, acceptance-tests-skipped, release/v1.4.x

#1482 ci: run security checks on push to branch
  .github/workflows/periodic-security-check.yaml
Labels: kind/bug, approved, lgtm, acceptance-tests-skipped, release/v1.4.x

#1488 test: retry app creation on failure
  test/acceptance/features/steps/openshift.py
Labels: kind/bug, approved, lgtm, release/v1.4.x
